flowchart LR
    v738ey1b5y(("EVAL<br>*v738ey1b5y*")) -- All True --> xo4l1ngx8q("NOP UI Page<br>*xo4l1ngx8q*")
    md8472gv2e("Show Success<br>*md8472gv2e*") -- All True --> v738ey1b5y(("EVAL<br>*v738ey1b5y*"))
    ixq0pq1td7(("EVAL<br>*ixq0pq1td7*")) -- All True --> 5vfn623mx7("Display password reset form<br>*5vfn623mx7*")
    mjqbph9elz(("EVAL<br>*mjqbph9elz*")) -- All True --> ur66q695u0("Go To: Show Success<br>*ur66q695u0*")
    d3ziqry02i(("EVAL<br>*d3ziqry02i*")) -- All True --> yo6nv4gud2("Go To: Success<br>*yo6nv4gud2*")
    d3ziqry02i(("EVAL<br>*d3ziqry02i*")) -- Any False --> jn53bcmsnv("Boolean Check<br>*jn53bcmsnv*")
    w0jz1dtx27("Verify Passwords Match<br>*w0jz1dtx27*") -- All True --> 6oeo7c9bch(("EVAL<br>*6oeo7c9bch*"))
    6oeo7c9bch(("EVAL<br>*6oeo7c9bch*")) -- All True --> 7eaxdz9nwk("Update password<br>*7eaxdz9nwk*")
    h330sqhk7o("Empty Check<br>*h330sqhk7o*") -- All True --> d3ziqry02i(("EVAL<br>*d3ziqry02i*"))
    mjqbph9elz(("EVAL<br>*mjqbph9elz*")) -- Any False --> ut2v2s6fqq("Go To: Success<br>*ut2v2s6fqq*")
    75iq81515r("Password reset submit?<br>*75iq81515r*") -- All True --> o5jvuf0bwl(("EVAL<br>*o5jvuf0bwl*"))
    79lag5unyk("NOP UI Page<br>*79lag5unyk*") -- All True --> a3oth8yspq(("EVAL<br>*a3oth8yspq*"))
    a3oth8yspq(("EVAL<br>*a3oth8yspq*")) -- All True --> 5vfn623mx7("Display password reset form<br>*5vfn623mx7*")
    ateb0l10nl(("EVAL<br>*ateb0l10nl*")) -- All True --> h330sqhk7o("Empty Check<br>*h330sqhk7o*")
    jn53bcmsnv("Boolean Check<br>*jn53bcmsnv*") -- All True --> mjqbph9elz(("EVAL<br>*mjqbph9elz*"))
    o5jvuf0bwl(("EVAL<br>*o5jvuf0bwl*")) -- All True --> dcq4ib3mce("Go To: Success<br>*dcq4ib3mce*")
    6oeo7c9bch(("EVAL<br>*6oeo7c9bch*")) -- Any False --> 2m4whqb1dr("Passwords dont match<br>*2m4whqb1dr*")
    wv79oxt1fo(("EVAL<br>*wv79oxt1fo*")) -- All True --> 9pswmi4mi1("Go To: Success<br>*9pswmi4mi1*")
    brpmsv8uag("Success Error<br>*brpmsv8uag*") -- All True --> b900rty9pd(("EVAL<br>*b900rty9pd*"))
    30owhg6lfp(("EVAL<br>*30owhg6lfp*")) -- All True --> 75iq81515r("Password reset submit?<br>*75iq81515r*")
    2inl0soj3i(("EVAL<br>*2inl0soj3i*")) -- All True --> w0jz1dtx27("Verify Passwords Match<br>*w0jz1dtx27*")
    7eaxdz9nwk("Update password<br>*7eaxdz9nwk*") -- All True --> ateb0l10nl(("EVAL<br>*ateb0l10nl*"))
    8qr5bc3clq("Success<br>*8qr5bc3clq*") -- All True --> jf9akdpa1q(("EVAL<br>*jf9akdpa1q*"))
    5vfn623mx7("Display password reset form<br>*5vfn623mx7*") -- All True --> 30owhg6lfp(("EVAL<br>*30owhg6lfp*"))
    75iq81515r("Password reset submit?<br>*75iq81515r*") -- All True --> 2inl0soj3i(("EVAL<br>*2inl0soj3i*"))
    4tnam70cjm("Send Success Response<br>*4tnam70cjm*") -- All True --> 2znw6pakac(("EVAL<br>*2znw6pakac*"))
    75iq81515r("Password reset submit?<br>*75iq81515r*") -- All True --> wv79oxt1fo(("EVAL<br>*wv79oxt1fo*"))
    b900rty9pd(("EVAL<br>*b900rty9pd*")) -- All True --> hxmqf7sb52("Send Error Response<br>*hxmqf7sb52*")
    xo4l1ngx8q("NOP UI Page<br>*xo4l1ngx8q*") -- All True --> ixq0pq1td7(("EVAL<br>*ixq0pq1td7*"))
    jf9akdpa1q(("EVAL<br>*jf9akdpa1q*")) -- All True --> 4tnam70cjm("Send Success Response<br>*4tnam70cjm*")
    2znw6pakac(("EVAL<br>*2znw6pakac*")) -- Any False --> uj42vvvgjt("Go To: Success Error<br>*uj42vvvgjt*")
    ym31re8b7g(("EVAL<br>*ym31re8b7g*")) -- All True --> okw0g6i84d("Update error message<br>*okw0g6i84d*")
    um3lcpaulo(("EVAL<br>*um3lcpaulo*")) -- All True --> abmzqz1u6f("Invalid password<br>*abmzqz1u6f*")
    okw0g6i84d("Update error message<br>*okw0g6i84d*") -- All True --> um3lcpaulo(("EVAL<br>*um3lcpaulo*"))
    rysh2x3iz2("Set error message<br>*rysh2x3iz2*") -- All True --> ym31re8b7g(("EVAL<br>*ym31re8b7g*"))
    ateb0l10nl(("EVAL<br>*ateb0l10nl*")) -- Any False --> rysh2x3iz2("Set error message<br>*rysh2x3iz2*")
    6oeo7c9bch(("EVAL<br>*6oeo7c9bch*")) -- All True --> t0vllny9q("Http<br>*t0vllny9q*")

    linkStyle 0 stroke:#5F84BB,stroke-width:2px;
    linkStyle 1 stroke:#5F84BB,stroke-width:2px;
    linkStyle 2 stroke:#5F84BB,stroke-width:2px;
    linkStyle 3 stroke:#5F84BB,stroke-width:2px;
    linkStyle 4 stroke:#5F84BB,stroke-width:2px;
    linkStyle 5 stroke:#FCBC3E,stroke-width:2px;
    linkStyle 6 stroke:#5F84BB,stroke-width:2px;
    linkStyle 7 stroke:#5F84BB,stroke-width:2px;
    linkStyle 8 stroke:#5F84BB,stroke-width:2px;
    linkStyle 9 stroke:#FCBC3E,stroke-width:2px;
    linkStyle 10 stroke:#5F84BB,stroke-width:2px;
    linkStyle 11 stroke:#5F84BB,stroke-width:2px;
    linkStyle 12 stroke:#5F84BB,stroke-width:2px;
    linkStyle 13 stroke:#5F84BB,stroke-width:2px;
    linkStyle 14 stroke:#5F84BB,stroke-width:2px;
    linkStyle 15 stroke:#5F84BB,stroke-width:2px;
    linkStyle 16 stroke:#FCBC3E,stroke-width:2px;
    linkStyle 17 stroke:#5F84BB,stroke-width:2px;
    linkStyle 18 stroke:#5F84BB,stroke-width:2px;
    linkStyle 19 stroke:#5F84BB,stroke-width:2px;
    linkStyle 20 stroke:#5F84BB,stroke-width:2px;
    linkStyle 21 stroke:#5F84BB,stroke-width:2px;
    linkStyle 22 stroke:#5F84BB,stroke-width:2px;
    linkStyle 23 stroke:#5F84BB,stroke-width:2px;
    linkStyle 24 stroke:#5F84BB,stroke-width:2px;
    linkStyle 25 stroke:#5F84BB,stroke-width:2px;
    linkStyle 26 stroke:#5F84BB,stroke-width:2px;
    linkStyle 27 stroke:#5F84BB,stroke-width:2px;
    linkStyle 28 stroke:#5F84BB,stroke-width:2px;
    linkStyle 29 stroke:#5F84BB,stroke-width:2px;
    linkStyle 30 stroke:#FCBC3E,stroke-width:2px;
    linkStyle 31 stroke:#5F84BB,stroke-width:2px;
    linkStyle 32 stroke:#5F84BB,stroke-width:2px;
    linkStyle 33 stroke:#5F84BB,stroke-width:2px;
    linkStyle 34 stroke:#5F84BB,stroke-width:2px;
    linkStyle 35 stroke:#FCBC3E,stroke-width:2px;
    linkStyle 36 stroke:#5F84BB,stroke-width:2px;
