flowchart LR
    mtaqacdw1m(("EVAL<br>*mtaqacdw1m*")) -- All True --> 8jrbqcts2g("Create MFA Device<br>*8jrbqcts2g*")
    hk00gx2f95(("EVAL<br>*hk00gx2f95*")) -- All True --> onogvjusk6("Prompt For OTP<br>*onogvjusk6*")
    qw4n733f3t(("EVAL<br>*qw4n733f3t*")) -- All True --> li0d8slgjx("Send email for new device<br>*li0d8slgjx*")
    7jufzmg1rk("Activate MFA Device<br>*7jufzmg1rk*") -- All True --> qw4n733f3t(("EVAL<br>*qw4n733f3t*"))
    8jrbqcts2g("Create MFA Device<br>*8jrbqcts2g*") -- All True --> hk00gx2f95(("EVAL<br>*hk00gx2f95*"))
    kho2rpwvb7(("EVAL<br>*kho2rpwvb7*")) -- All True --> 7jufzmg1rk("Activate MFA Device<br>*7jufzmg1rk*")
    onogvjusk6("Prompt For OTP<br>*onogvjusk6*") -- All True --> kho2rpwvb7(("EVAL<br>*kho2rpwvb7*"))
    78i0a08xfl("Send email for threat detection<br>*78i0a08xfl*") -- All True --> iz5nper189(("EVAL<br>*iz5nper189*"))
    gsmghrxxoy("Check for KNOWN DEVICE<br>*gsmghrxxoy*") -- All True --> nl0cxyid0x(("EVAL<br>*nl0cxyid0x*"))
    99q38lg97t(("EVAL<br>*99q38lg97t*")) -- All True --> sqdggkol0g("Go To: Error<br>*sqdggkol0g*")
    iloobtovwh(("EVAL<br>*iloobtovwh*")) -- All True --> dxowhkk5n5("Check if Risk Policy ID is empty<br>*dxowhkk5n5*")
    iz5nper189(("EVAL<br>*iz5nper189*")) -- All True --> 7hwtzuxjwc("Disable user<br>*7hwtzuxjwc*")
    n69ynlsgag(("EVAL<br>*n69ynlsgag*")) -- All True --> nf4hv96sui("Check MFA devices size<br>*nf4hv96sui*")
    cb4rka2li0(("EVAL<br>*cb4rka2li0*")) -- All True --> 78i0a08xfl("Send email for threat detection<br>*78i0a08xfl*")
    x8ainlbr6x(("EVAL<br>*x8ainlbr6x*")) -- All True --> ndm5er34sv("Risk Score from PingOne Protect<br>*ndm5er34sv*")
    j6salon8z4("Get Values from PingOne Protect analysis<br>*j6salon8z4*") -- All True --> cb4rka2li0(("EVAL<br>*cb4rka2li0*"))
    ahjplbui3q("PingOne Notifications<br>*ahjplbui3q*") -- All True --> x8ainlbr6x(("EVAL<br>*x8ainlbr6x*"))
    pt24r4nafa(("EVAL<br>*pt24r4nafa*")) -- All True --> 3y03qc0kxe("Find user details<br>*3y03qc0kxe*")
    mtaqacdw1m(("EVAL<br>*mtaqacdw1m*")) -- Any False --> 5231692i67("Return to calling node.<br>*5231692i67*")
    4oyc5l9npk(("EVAL<br>*4oyc5l9npk*")) -- All True --> 737gi6ip3e("Go To: PingOne Protect Analysis<br>*737gi6ip3e*")
    u22hch23vs(("EVAL<br>*u22hch23vs*")) -- All True --> gsmghrxxoy("Check for KNOWN DEVICE<br>*gsmghrxxoy*")
    zfpuewwuhl("PingOne Protect Analysis<br>*zfpuewwuhl*") -- All True --> pt24r4nafa(("EVAL<br>*pt24r4nafa*"))
    3y03qc0kxe("Find user details<br>*3y03qc0kxe*") -- All True --> qxdd8mlll5(("EVAL<br>*qxdd8mlll5*"))
    nl0cxyid0x(("EVAL<br>*nl0cxyid0x*")) -- Any False --> ahjplbui3q("PingOne Notifications<br>*ahjplbui3q*")
    li0d8slgjx("Send email for new device<br>*li0d8slgjx*") -- All True --> e3httj56zd(("EVAL<br>*e3httj56zd*"))
    737gi6ip3e("Go To: PingOne Protect Analysis<br>*737gi6ip3e*") -- All True --> 9vk797lpxx(("EVAL<br>*9vk797lpxx*"))
    nf4hv96sui("Check MFA devices size<br>*nf4hv96sui*") -- All True --> mtaqacdw1m(("EVAL<br>*mtaqacdw1m*"))
    1cbcpbc5no(("EVAL<br>*1cbcpbc5no*")) -- All True --> 4psx471uwp("Authentication Required<br>*4psx471uwp*")
    h8dtvwld36(("EVAL<br>*h8dtvwld36*")) -- All True --> 76reddil11("Go To: FIDO2<br>*76reddil11*")
    r0hto2xun7("Present OTP Form<br>*r0hto2xun7*") -- All True --> l5z3ngnhjv(("EVAL<br>*l5z3ngnhjv*"))
    1gtc5d0awz(("EVAL<br>*1gtc5d0awz*")) -- All True --> kok73n8hkt("Go To: OTP<br>*kok73n8hkt*")
    4psx471uwp("Authentication Required<br>*4psx471uwp*") -- All True --> 1gtc5d0awz(("EVAL<br>*1gtc5d0awz*"))
    qurffyxc2d("Split by user selection <br>*qurffyxc2d*") -- All True --> gsw5wwtm7t(("EVAL<br>*gsw5wwtm7t*"))
    en7y953x31("Get authMethod Value<br>*en7y953x31*") -- All True --> 0w6twuixxq(("EVAL<br>*0w6twuixxq*"))
    fzjj3nuh7m(("EVAL<br>*fzjj3nuh7m*")) -- Any False --> dxsjn36392("Go To: Error<br>*dxsjn36392*")
    mt9kvt7hnn(("EVAL<br>*mt9kvt7hnn*")) -- All True --> fgc8woctfo("Validate Passcode<br>*fgc8woctfo*")
    qurffyxc2d("Split by user selection <br>*qurffyxc2d*") -- All True --> 00j11fkhbx(("EVAL<br>*00j11fkhbx*"))
    fzjj3nuh7m(("EVAL<br>*fzjj3nuh7m*")) -- All True --> uz6hhdt9gv("OTP Resent Message<br>*uz6hhdt9gv*")
    zxfluj3oxa("OTP<br>*zxfluj3oxa*") -- All True --> b0csz8cgnl(("EVAL<br>*b0csz8cgnl*"))
    qurffyxc2d("Split by user selection <br>*qurffyxc2d*") -- All True --> ig2ndq8bf2(("EVAL<br>*ig2ndq8bf2*"))
    00j11fkhbx(("EVAL<br>*00j11fkhbx*")) -- All True --> beakf43h8t("Go To: Device Selection<br>*beakf43h8t*")
    gsw5wwtm7t(("EVAL<br>*gsw5wwtm7t*")) -- All True --> r6lnkuy0yh("Transform Passcode To Lowercase<br>*r6lnkuy0yh*")
    ig2ndq8bf2(("EVAL<br>*ig2ndq8bf2*")) -- All True --> m1e0cw0ygl("Resend OTP<br>*m1e0cw0ygl*")
    m1e0cw0ygl("Resend OTP<br>*m1e0cw0ygl*") -- All True --> fzjj3nuh7m(("EVAL<br>*fzjj3nuh7m*"))
    r6lnkuy0yh("Transform Passcode To Lowercase<br>*r6lnkuy0yh*") -- All True --> mt9kvt7hnn(("EVAL<br>*mt9kvt7hnn*"))
    hdc8oa72ci("Is invalidOTP Error<br>*hdc8oa72ci*") -- All True --> 8h5tjkrug9(("EVAL<br>*8h5tjkrug9*"))
    v97rmwpban(("EVAL<br>*v97rmwpban*")) -- All True --> 5pixttpidw("Invalid Passcode Error<br>*5pixttpidw*")
    gntsn38l9s("CIAM - Magic Link Authentication<br>*gntsn38l9s*") -- All True --> 51zazld6jz(("EVAL<br>*51zazld6jz*"))
    5uyrxkfgza(("EVAL<br>*5uyrxkfgza*")) -- All True --> tidk1pmqix("Return Success Response<br>*tidk1pmqix*")
    8h5tjkrug9(("EVAL<br>*8h5tjkrug9*")) -- All True --> mmojm56jlj("Go To: Error<br>*mmojm56jlj*")
    uoyh9kzwil("Device Selection<br>*uoyh9kzwil*") -- All True --> bhgtvbjvu1(("EVAL<br>*bhgtvbjvu1*"))
    se271xaurx(("EVAL<br>*se271xaurx*")) -- Any False --> uwfrx6s60u("Go To: Error<br>*uwfrx6s60u*")
    vr1msssq3l(("EVAL<br>*vr1msssq3l*")) -- All True --> wpbqyomp7z("Go To: Success <br>*wpbqyomp7z*")
    wa07p8s7qm("Not Magic Link?<br>*wa07p8s7qm*") -- All True --> vr1msssq3l(("EVAL<br>*vr1msssq3l*"))
    vul5k2q2dw(("EVAL<br>*vul5k2q2dw*")) -- All True --> te0bcdks99("Magic Link Authentication<br>*te0bcdks99*")
    wa07p8s7qm("Not Magic Link?<br>*wa07p8s7qm*") -- All True --> vul5k2q2dw(("EVAL<br>*vul5k2q2dw*"))
    imhudhsy1w(("EVAL<br>*imhudhsy1w*")) -- All True --> e717up82dy("Device Selected By The User<br>*e717up82dy*")
    wa07p8s7qm("Not Magic Link?<br>*wa07p8s7qm*") -- All True --> imhudhsy1w(("EVAL<br>*imhudhsy1w*"))
    j8lmuiytzs("Is MFA Enabled?<br>*j8lmuiytzs*") -- All True --> bf9jlbogz1(("EVAL<br>*bf9jlbogz1*"))
    bhgtvbjvu1(("EVAL<br>*bhgtvbjvu1*")) -- All True --> 1qtib8s0uu("Select Authentication Device<br>*1qtib8s0uu*")
    0sua91hqk7(("EVAL<br>*0sua91hqk7*")) -- All True --> 10oaokas61("Start MFA Authentication<br>*10oaokas61*")
    845xzgf4bk(("EVAL<br>*845xzgf4bk*")) -- Any False --> ulsqznx6ut("Is Constraint Violation Error<br>*ulsqznx6ut*")
    51zazld6jz(("EVAL<br>*51zazld6jz*")) -- All True --> 5gs9h0ar04("Go To: Success <br>*5gs9h0ar04*")
    3a77bpgwom(("EVAL<br>*3a77bpgwom*")) -- All True --> y7f8x8dkw2("Go To: Error<br>*y7f8x8dkw2*")
    zfsjjfa5h6("Present FIDO2 Form <br>*zfsjjfa5h6*") -- All True --> 9pb86bg0qi(("EVAL<br>*9pb86bg0qi*"))
    wf0h6fo6h8("Split By Users Selection<br>*wf0h6fo6h8*") -- All True --> ay2mm4z4xe(("EVAL<br>*ay2mm4z4xe*"))
    ulsqznx6ut("Is Constraint Violation Error<br>*ulsqznx6ut*") -- All True --> fu06ckn12l(("EVAL<br>*fu06ckn12l*"))
    fj8w62y4z3("Assert FIDO Device Authentication<br>*fj8w62y4z3*") -- All True --> 845xzgf4bk(("EVAL<br>*845xzgf4bk*"))
    fu06ckn12l(("EVAL<br>*fu06ckn12l*")) -- All True --> y8pxpynfle("Invalid Device Error<br>*y8pxpynfle*")
    7vrrd3uuhm(("EVAL<br>*7vrrd3uuhm*")) -- All True --> en7y953x31("Get authMethod Value<br>*en7y953x31*")
    1lam7h7jbc("Split By Subflows Result<br>*1lam7h7jbc*") -- All True --> 9fzm9oj8fd(("EVAL<br>*9fzm9oj8fd*"))
    qsu3efxcsp(("EVAL<br>*qsu3efxcsp*")) -- All True --> 1lam7h7jbc("Split By Subflows Result<br>*1lam7h7jbc*")
    6yu5p2iz3r(("EVAL<br>*6yu5p2iz3r*")) -- All True --> ms19ql02hi("Get MFA Status<br>*ms19ql02hi*")
    en7y953x31("Get authMethod Value<br>*en7y953x31*") -- All True --> 0w6twuixxq(("EVAL<br>*0w6twuixxq*"))
    t6p5s6t603("Get WebAuthn Browser Compatibility<br>*t6p5s6t603*") -- All True --> 4oyc5l9npk(("EVAL<br>*4oyc5l9npk*"))
    10uwd1ccc4("Filter Unusable Devices<br>*10uwd1ccc4*") -- All True --> se271xaurx(("EVAL<br>*se271xaurx*"))
    wzzac3ucto("Create Masked Devices<br>*wzzac3ucto*") -- All True --> 6yu5p2iz3r(("EVAL<br>*6yu5p2iz3r*"))
    fd7o3icva4(("EVAL<br>*fd7o3icva4*")) -- All True --> j8lmuiytzs("Is MFA Enabled?<br>*j8lmuiytzs*")
    ms19ql02hi("Get MFA Status<br>*ms19ql02hi*") -- All True --> fd7o3icva4(("EVAL<br>*fd7o3icva4*"))
    3nn0mw8jkt(("EVAL<br>*3nn0mw8jkt*")) -- All True --> 61c9e2dt59("Go To: Device Selection<br>*61c9e2dt59*")
    51zazld6jz(("EVAL<br>*51zazld6jz*")) -- Any False --> nvxwg0vum3("Go To: Error<br>*nvxwg0vum3*")
    9fzm9oj8fd(("EVAL<br>*9fzm9oj8fd*")) -- All True --> lgn9kliiqj("Go To: Success <br>*lgn9kliiqj*")
    b0csz8cgnl(("EVAL<br>*b0csz8cgnl*")) -- All True --> fq7l0s8w2s("Mask Device<br>*fq7l0s8w2s*")
    1lam7h7jbc("Split By Subflows Result<br>*1lam7h7jbc*") -- All True --> lylme68jbw(("EVAL<br>*lylme68jbw*"))
    0w6twuixxq(("EVAL<br>*0w6twuixxq*")) -- All True --> 5sb0db3vb0("Go To: Success <br>*5sb0db3vb0*")
    7vpjww2ek2("FIDO2<br>*7vpjww2ek2*") -- All True --> t04dles3gs(("EVAL<br>*t04dles3gs*"))
    9vk797lpxx(("EVAL<br>*9vk797lpxx*")) -- All True --> 10uwd1ccc4("Filter Unusable Devices<br>*10uwd1ccc4*")
    wf0h6fo6h8("Split By Users Selection<br>*wf0h6fo6h8*") -- All True --> 3nn0mw8jkt(("EVAL<br>*3nn0mw8jkt*"))
    k46n95w9eo("Success <br>*k46n95w9eo*") -- All True --> 5uyrxkfgza(("EVAL<br>*5uyrxkfgza*"))
    hdc8oa72ci("Is invalidOTP Error<br>*hdc8oa72ci*") -- All True --> v97rmwpban(("EVAL<br>*v97rmwpban*"))
    7vrrd3uuhm(("EVAL<br>*7vrrd3uuhm*")) -- Any False --> hdc8oa72ci("Is invalidOTP Error<br>*hdc8oa72ci*")
    fgc8woctfo("Validate Passcode<br>*fgc8woctfo*") -- All True --> 7vrrd3uuhm(("EVAL<br>*7vrrd3uuhm*"))
    zbhvblc83s("Authentication Method Selection<br>*zbhvblc83s*") -- All True --> ybwxgols9w(("EVAL<br>*ybwxgols9w*"))
    4psx471uwp("Authentication Required<br>*4psx471uwp*") -- All True --> h8dtvwld36(("EVAL<br>*h8dtvwld36*"))
    ybwxgols9w(("EVAL<br>*ybwxgols9w*")) -- All True --> 9zctbmveoc("Enrich Device Details<br>*9zctbmveoc*")
    iloobtovwh(("EVAL<br>*iloobtovwh*")) -- All True --> dwhgyxkavz("Error Error Response<br>*dwhgyxkavz*")
    qsu3efxcsp(("EVAL<br>*qsu3efxcsp*")) -- Any False --> muund54c7j("Go To: Error<br>*muund54c7j*")
    6p4frzqpp1("Get Origin<br>*6p4frzqpp1*") -- All True --> sk7vd2o3r7(("EVAL<br>*sk7vd2o3r7*"))
    845xzgf4bk(("EVAL<br>*845xzgf4bk*")) -- All True --> dp43hy7h76("Get authMethod Value<br>*dp43hy7h76*")
    5v1i2f1az4(("EVAL<br>*5v1i2f1az4*")) -- Any False --> cbapcifpyy("Go To: Error<br>*cbapcifpyy*")
    nydopq0ve3(("EVAL<br>*nydopq0ve3*")) -- Any False --> qzuk2c4cdb("Go To: Error<br>*qzuk2c4cdb*")
    nydopq0ve3(("EVAL<br>*nydopq0ve3*")) -- All True --> t6p5s6t603("Get WebAuthn Browser Compatibility<br>*t6p5s6t603*")
    fq7l0s8w2s("Mask Device<br>*fq7l0s8w2s*") -- All True --> bdjeulfdki(("EVAL<br>*bdjeulfdki*"))
    jd87iaho99("Error<br>*jd87iaho99*") -- All True --> iloobtovwh(("EVAL<br>*iloobtovwh*"))
    7vz1yqkdqo(("EVAL<br>*7vz1yqkdqo*")) -- All True --> gntsn38l9s("CIAM - Magic Link Authentication<br>*gntsn38l9s*")
    bdjeulfdki(("EVAL<br>*bdjeulfdki*")) -- All True --> r0hto2xun7("Present OTP Form<br>*r0hto2xun7*")
    9m5a2f4emp("Get Users Existing Devices<br>*9m5a2f4emp*") -- All True --> nydopq0ve3(("EVAL<br>*nydopq0ve3*"))
    dp43hy7h76("Get authMethod Value<br>*dp43hy7h76*") -- All True --> zep1ojf98g(("EVAL<br>*zep1ojf98g*"))
    czzrbt1dsb("Magic Link Enabled<br>*czzrbt1dsb*") -- All True --> 7vz1yqkdqo(("EVAL<br>*7vz1yqkdqo*"))
    ulsqznx6ut("Is Constraint Violation Error<br>*ulsqznx6ut*") -- All True --> 3a77bpgwom(("EVAL<br>*3a77bpgwom*"))
    ay2mm4z4xe(("EVAL<br>*ay2mm4z4xe*")) -- All True --> fj8w62y4z3("Assert FIDO Device Authentication<br>*fj8w62y4z3*")
    0sua91hqk7(("EVAL<br>*0sua91hqk7*")) -- Any False --> czzrbt1dsb("Magic Link Enabled<br>*czzrbt1dsb*")
    sk7vd2o3r7(("EVAL<br>*sk7vd2o3r7*")) -- All True --> 9m5a2f4emp("Get Users Existing Devices<br>*9m5a2f4emp*")
    lylme68jbw(("EVAL<br>*lylme68jbw*")) -- All True --> fkkub10ukt("Go To: Device Selection<br>*fkkub10ukt*")
    zep1ojf98g(("EVAL<br>*zep1ojf98g*")) -- All True --> 9f0dokmcu9("Go To: Success <br>*9f0dokmcu9*")
    10oaokas61("Start MFA Authentication<br>*10oaokas61*") -- All True --> 4l39ap532m(("EVAL<br>*4l39ap532m*"))
    47qta86y95(("EVAL<br>*47qta86y95*")) -- Any False --> x0jx5r2pyd("Go To: Error<br>*x0jx5r2pyd*")
    frh74jp1jg("Only One Usable Device<br>*frh74jp1jg*") -- All True --> ydyrhm9fkz(("EVAL<br>*ydyrhm9fkz*"))
    47qta86y95(("EVAL<br>*47qta86y95*")) -- All True --> wphj1fy8ri("Go To: Authentication Method Selection<br>*wphj1fy8ri*")
    b01n00fwkm("Continue MFA With Only Device<br>*b01n00fwkm*") -- All True --> 47qta86y95(("EVAL<br>*47qta86y95*"))
    7vz1yqkdqo(("EVAL<br>*7vz1yqkdqo*")) -- Any False --> 2uhj1oobbe("Go To: Error<br>*2uhj1oobbe*")
    4l39ap532m(("EVAL<br>*4l39ap532m*")) -- All True --> icy7kw57ll("Authentication Prompt<br>*icy7kw57ll*")
    icy7kw57ll("Authentication Prompt<br>*icy7kw57ll*") -- All True --> v0t14r4lv2(("EVAL<br>*v0t14r4lv2*"))
    v0t14r4lv2(("EVAL<br>*v0t14r4lv2*")) -- All True --> frh74jp1jg("Only One Usable Device<br>*frh74jp1jg*")
    4l39ap532m(("EVAL<br>*4l39ap532m*")) -- Any False --> t4cuk82upd("Go To: Error<br>*t4cuk82upd*")
    icy7kw57ll("Authentication Prompt<br>*icy7kw57ll*") -- All True --> wj5284rjb8(("EVAL<br>*wj5284rjb8*"))
    wj5284rjb8(("EVAL<br>*wj5284rjb8*")) -- All True --> l7i5qjffz1("Go To: Authentication Method Selection<br>*l7i5qjffz1*")
    icy7kw57ll("Authentication Prompt<br>*icy7kw57ll*") -- All True --> vw8zbuzgod(("EVAL<br>*vw8zbuzgod*"))
    vw8zbuzgod(("EVAL<br>*vw8zbuzgod*")) -- All True --> j55n69o5i7("Go To: Authentication Method Selection<br>*j55n69o5i7*")
    ydyrhm9fkz(("EVAL<br>*ydyrhm9fkz*")) -- Any False --> a58tdqlgfb("Go To: Device Selection<br>*a58tdqlgfb*")
    t04dles3gs(("EVAL<br>*t04dles3gs*")) -- All True --> zfsjjfa5h6("Present FIDO2 Form <br>*zfsjjfa5h6*")
    5v1i2f1az4(("EVAL<br>*5v1i2f1az4*")) -- All True --> 4vf8sqyl70("Go To: Authentication Method Selection<br>*4vf8sqyl70*")
    9pb86bg0qi(("EVAL<br>*9pb86bg0qi*")) -- All True --> wf0h6fo6h8("Split By Users Selection<br>*wf0h6fo6h8*")
    1qtib8s0uu("Select Authentication Device<br>*1qtib8s0uu*") -- All True --> iagfrg0an6(("EVAL<br>*iagfrg0an6*"))
    e717up82dy("Device Selected By The User<br>*e717up82dy*") -- All True --> 5v1i2f1az4(("EVAL<br>*5v1i2f1az4*"))
    bf9jlbogz1(("EVAL<br>*bf9jlbogz1*")) -- All True --> 2n3az4vori("User Has Active Devices<br>*2n3az4vori*")
    iagfrg0an6(("EVAL<br>*iagfrg0an6*")) -- All True --> wa07p8s7qm("Not Magic Link?<br>*wa07p8s7qm*")
    bf9jlbogz1(("EVAL<br>*bf9jlbogz1*")) -- Any False --> czzrbt1dsb("Magic Link Enabled<br>*czzrbt1dsb*")
    2n3az4vori("User Has Active Devices<br>*2n3az4vori*") -- All True --> 0sua91hqk7(("EVAL<br>*0sua91hqk7*"))
    te0bcdks99("Magic Link Authentication<br>*te0bcdks99*") -- All True --> qsu3efxcsp(("EVAL<br>*qsu3efxcsp*"))
    ydyrhm9fkz(("EVAL<br>*ydyrhm9fkz*")) -- All True --> xsm25p5qf7("Magic Link Enabled<br>*xsm25p5qf7*")
    xsm25p5qf7("Magic Link Enabled<br>*xsm25p5qf7*") -- All True --> ayodtok1lb(("EVAL<br>*ayodtok1lb*"))
    ayodtok1lb(("EVAL<br>*ayodtok1lb*")) -- All True --> x9k0uusly8("Go To: Device Selection<br>*x9k0uusly8*")
    ayodtok1lb(("EVAL<br>*ayodtok1lb*")) -- Any False --> b01n00fwkm("Continue MFA With Only Device<br>*b01n00fwkm*")
    9zctbmveoc("Enrich Device Details<br>*9zctbmveoc*") -- All True --> 1cbcpbc5no(("EVAL<br>*1cbcpbc5no*"))
    l5z3ngnhjv(("EVAL<br>*l5z3ngnhjv*")) -- All True --> qurffyxc2d("Split by user selection <br>*qurffyxc2d*")
    se271xaurx(("EVAL<br>*se271xaurx*")) -- All True --> wzzac3ucto("Create Masked Devices<br>*wzzac3ucto*")
    sk3dza5671(("EVAL<br>*sk3dza5671*")) -- All True --> di86a7q7j0("Go To: Error<br>*di86a7q7j0*")
    e3httj56zd(("EVAL<br>*e3httj56zd*")) -- Any False --> 5231692i67("Return to calling node.<br>*5231692i67*")
    qxdd8mlll5(("EVAL<br>*qxdd8mlll5*")) -- All True --> u9ab712lfx("Invoke PingOne Protect subflow<br>*u9ab712lfx*")
    u9ab712lfx("Invoke PingOne Protect subflow<br>*u9ab712lfx*") -- All True --> vexxoicu6a(("EVAL<br>*vexxoicu6a*"))
    vexxoicu6a(("EVAL<br>*vexxoicu6a*")) -- All True --> 3s5kidc2wc("Get Values from PingOne Protect analysis<br>*3s5kidc2wc*")
    vexxoicu6a(("EVAL<br>*vexxoicu6a*")) -- Any False --> j6salon8z4("Get Values from PingOne Protect analysis<br>*j6salon8z4*")
    3s5kidc2wc("Get Values from PingOne Protect analysis<br>*3s5kidc2wc*") -- All True --> u22hch23vs(("EVAL<br>*u22hch23vs*"))
    nl0cxyid0x(("EVAL<br>*nl0cxyid0x*")) -- All True --> ndm5er34sv("Risk Score from PingOne Protect<br>*ndm5er34sv*")
    ndm5er34sv("Risk Score from PingOne Protect<br>*ndm5er34sv*") -- All True --> 4n12f0orqv(("EVAL<br>*4n12f0orqv*"))
    4n12f0orqv(("EVAL<br>*4n12f0orqv*")) -- All True --> d2uumx5mpk("Return to calling node<br>*d2uumx5mpk*")
    ndm5er34sv("Risk Score from PingOne Protect<br>*ndm5er34sv*") -- All True --> n69ynlsgag(("EVAL<br>*n69ynlsgag*"))
    7hwtzuxjwc("Disable user<br>*7hwtzuxjwc*") -- All True --> 99q38lg97t(("EVAL<br>*99q38lg97t*"))
    ndm5er34sv("Risk Score from PingOne Protect<br>*ndm5er34sv*") -- All True --> sk3dza5671(("EVAL<br>*sk3dza5671*"))
    kgxiu8h9i5(("EVAL<br>*kgxiu8h9i5*")) -- All True --> 9w2fwmdjtp("PingOne Protect Risk ID is Empty/NULL<br>*9w2fwmdjtp*")
    qw4n733f3t(("EVAL<br>*qw4n733f3t*")) -- Any False --> sj6aezm25b("Go To: Error<br>*sj6aezm25b*")
    dxowhkk5n5("Check if Risk Policy ID is empty<br>*dxowhkk5n5*") -- All True --> kgxiu8h9i5(("EVAL<br>*kgxiu8h9i5*"))
    kgxiu8h9i5(("EVAL<br>*kgxiu8h9i5*")) -- Any False --> p3914imkz7("Update Risk Evaluation - FAILURE<br>*p3914imkz7*")
    5uyrxkfgza(("EVAL<br>*5uyrxkfgza*")) -- All True --> wi6hu0ai62("Check if Risk Policy ID is empty<br>*wi6hu0ai62*")
    wi6hu0ai62("Check if Risk Policy ID is empty<br>*wi6hu0ai62*") -- All True --> 33jpsgsdxv(("EVAL<br>*33jpsgsdxv*"))
    33jpsgsdxv(("EVAL<br>*33jpsgsdxv*")) -- Any False --> ilu6o9n2x7("Update Risk Evaluation - SUCCESS<br>*ilu6o9n2x7*")
    33jpsgsdxv(("EVAL<br>*33jpsgsdxv*")) -- All True --> 33kryo3flh("PingOne Protect Risk ID is Empty/NULL<br>*33kryo3flh*")
    fd7o3icva4(("EVAL<br>*fd7o3icva4*")) -- Any False --> 9q9zj5ndao("Go To: Error<br>*9q9zj5ndao*")

    linkStyle 0 stroke:#5F84BB,stroke-width:2px;
    linkStyle 1 stroke:#5F84BB,stroke-width:2px;
    linkStyle 2 stroke:#5F84BB,stroke-width:2px;
    linkStyle 3 stroke:#5F84BB,stroke-width:2px;
    linkStyle 4 stroke:#5F84BB,stroke-width:2px;
    linkStyle 5 stroke:#5F84BB,stroke-width:2px;
    linkStyle 6 stroke:#5F84BB,stroke-width:2px;
    linkStyle 7 stroke:#5F84BB,stroke-width:2px;
    linkStyle 8 stroke:#5F84BB,stroke-width:2px;
    linkStyle 9 stroke:#5F84BB,stroke-width:2px;
    linkStyle 10 stroke:#5F84BB,stroke-width:2px;
    linkStyle 11 stroke:#5F84BB,stroke-width:2px;
    linkStyle 12 stroke:#5F84BB,stroke-width:2px;
    linkStyle 13 stroke:#5F84BB,stroke-width:2px;
    linkStyle 14 stroke:#5F84BB,stroke-width:2px;
    linkStyle 15 stroke:#5F84BB,stroke-width:2px;
    linkStyle 16 stroke:#5F84BB,stroke-width:2px;
    linkStyle 17 stroke:#5F84BB,stroke-width:2px;
    linkStyle 18 stroke:#FCBC3E,stroke-width:2px;
    linkStyle 19 stroke:#5F84BB,stroke-width:2px;
    linkStyle 20 stroke:#5F84BB,stroke-width:2px;
    linkStyle 21 stroke:#5F84BB,stroke-width:2px;
    linkStyle 22 stroke:#5F84BB,stroke-width:2px;
    linkStyle 23 stroke:#FCBC3E,stroke-width:2px;
    linkStyle 24 stroke:#5F84BB,stroke-width:2px;
    linkStyle 25 stroke:#5F84BB,stroke-width:2px;
    linkStyle 26 stroke:#5F84BB,stroke-width:2px;
    linkStyle 27 stroke:#5F84BB,stroke-width:2px;
    linkStyle 28 stroke:#5F84BB,stroke-width:2px;
    linkStyle 29 stroke:#5F84BB,stroke-width:2px;
    linkStyle 30 stroke:#5F84BB,stroke-width:2px;
    linkStyle 31 stroke:#5F84BB,stroke-width:2px;
    linkStyle 32 stroke:#5F84BB,stroke-width:2px;
    linkStyle 33 stroke:#5F84BB,stroke-width:2px;
    linkStyle 34 stroke:#FCBC3E,stroke-width:2px;
    linkStyle 35 stroke:#5F84BB,stroke-width:2px;
    linkStyle 36 stroke:#5F84BB,stroke-width:2px;
    linkStyle 37 stroke:#5F84BB,stroke-width:2px;
    linkStyle 38 stroke:#5F84BB,stroke-width:2px;
    linkStyle 39 stroke:#5F84BB,stroke-width:2px;
    linkStyle 40 stroke:#5F84BB,stroke-width:2px;
    linkStyle 41 stroke:#5F84BB,stroke-width:2px;
    linkStyle 42 stroke:#5F84BB,stroke-width:2px;
    linkStyle 43 stroke:#5F84BB,stroke-width:2px;
    linkStyle 44 stroke:#5F84BB,stroke-width:2px;
    linkStyle 45 stroke:#5F84BB,stroke-width:2px;
    linkStyle 46 stroke:#5F84BB,stroke-width:2px;
    linkStyle 47 stroke:#5F84BB,stroke-width:2px;
    linkStyle 48 stroke:#5F84BB,stroke-width:2px;
    linkStyle 49 stroke:#5F84BB,stroke-width:2px;
    linkStyle 50 stroke:#5F84BB,stroke-width:2px;
    linkStyle 51 stroke:#FCBC3E,stroke-width:2px;
    linkStyle 52 stroke:#5F84BB,stroke-width:2px;
    linkStyle 53 stroke:#5F84BB,stroke-width:2px;
    linkStyle 54 stroke:#5F84BB,stroke-width:2px;
    linkStyle 55 stroke:#5F84BB,stroke-width:2px;
    linkStyle 56 stroke:#5F84BB,stroke-width:2px;
    linkStyle 57 stroke:#5F84BB,stroke-width:2px;
    linkStyle 58 stroke:#5F84BB,stroke-width:2px;
    linkStyle 59 stroke:#5F84BB,stroke-width:2px;
    linkStyle 60 stroke:#5F84BB,stroke-width:2px;
    linkStyle 61 stroke:#FCBC3E,stroke-width:2px;
    linkStyle 62 stroke:#5F84BB,stroke-width:2px;
    linkStyle 63 stroke:#5F84BB,stroke-width:2px;
    linkStyle 64 stroke:#5F84BB,stroke-width:2px;
    linkStyle 65 stroke:#5F84BB,stroke-width:2px;
    linkStyle 66 stroke:#5F84BB,stroke-width:2px;
    linkStyle 67 stroke:#5F84BB,stroke-width:2px;
    linkStyle 68 stroke:#5F84BB,stroke-width:2px;
    linkStyle 69 stroke:#5F84BB,stroke-width:2px;
    linkStyle 70 stroke:#5F84BB,stroke-width:2px;
    linkStyle 71 stroke:#5F84BB,stroke-width:2px;
    linkStyle 72 stroke:#5F84BB,stroke-width:2px;
    linkStyle 73 stroke:#5F84BB,stroke-width:2px;
    linkStyle 74 stroke:#5F84BB,stroke-width:2px;
    linkStyle 75 stroke:#5F84BB,stroke-width:2px;
    linkStyle 76 stroke:#5F84BB,stroke-width:2px;
    linkStyle 77 stroke:#5F84BB,stroke-width:2px;
    linkStyle 78 stroke:#5F84BB,stroke-width:2px;
    linkStyle 79 stroke:#5F84BB,stroke-width:2px;
    linkStyle 80 stroke:#FCBC3E,stroke-width:2px;
    linkStyle 81 stroke:#5F84BB,stroke-width:2px;
    linkStyle 82 stroke:#5F84BB,stroke-width:2px;
    linkStyle 83 stroke:#5F84BB,stroke-width:2px;
    linkStyle 84 stroke:#5F84BB,stroke-width:2px;
    linkStyle 85 stroke:#5F84BB,stroke-width:2px;
    linkStyle 86 stroke:#5F84BB,stroke-width:2px;
    linkStyle 87 stroke:#5F84BB,stroke-width:2px;
    linkStyle 88 stroke:#5F84BB,stroke-width:2px;
    linkStyle 89 stroke:#5F84BB,stroke-width:2px;
    linkStyle 90 stroke:#FCBC3E,stroke-width:2px;
    linkStyle 91 stroke:#5F84BB,stroke-width:2px;
    linkStyle 92 stroke:#5F84BB,stroke-width:2px;
    linkStyle 93 stroke:#5F84BB,stroke-width:2px;
    linkStyle 94 stroke:#5F84BB,stroke-width:2px;
    linkStyle 95 stroke:#5F84BB,stroke-width:2px;
    linkStyle 96 stroke:#FCBC3E,stroke-width:2px;
    linkStyle 97 stroke:#5F84BB,stroke-width:2px;
    linkStyle 98 stroke:#5F84BB,stroke-width:2px;
    linkStyle 99 stroke:#FCBC3E,stroke-width:2px;
    linkStyle 100 stroke:#FCBC3E,stroke-width:2px;
    linkStyle 101 stroke:#5F84BB,stroke-width:2px;
    linkStyle 102 stroke:#5F84BB,stroke-width:2px;
    linkStyle 103 stroke:#5F84BB,stroke-width:2px;
    linkStyle 104 stroke:#5F84BB,stroke-width:2px;
    linkStyle 105 stroke:#5F84BB,stroke-width:2px;
    linkStyle 106 stroke:#5F84BB,stroke-width:2px;
    linkStyle 107 stroke:#5F84BB,stroke-width:2px;
    linkStyle 108 stroke:#5F84BB,stroke-width:2px;
    linkStyle 109 stroke:#5F84BB,stroke-width:2px;
    linkStyle 110 stroke:#5F84BB,stroke-width:2px;
    linkStyle 111 stroke:#FCBC3E,stroke-width:2px;
    linkStyle 112 stroke:#5F84BB,stroke-width:2px;
    linkStyle 113 stroke:#5F84BB,stroke-width:2px;
    linkStyle 114 stroke:#5F84BB,stroke-width:2px;
    linkStyle 115 stroke:#5F84BB,stroke-width:2px;
    linkStyle 116 stroke:#FCBC3E,stroke-width:2px;
    linkStyle 117 stroke:#5F84BB,stroke-width:2px;
    linkStyle 118 stroke:#5F84BB,stroke-width:2px;
    linkStyle 119 stroke:#5F84BB,stroke-width:2px;
    linkStyle 120 stroke:#FCBC3E,stroke-width:2px;
    linkStyle 121 stroke:#5F84BB,stroke-width:2px;
    linkStyle 122 stroke:#5F84BB,stroke-width:2px;
    linkStyle 123 stroke:#5F84BB,stroke-width:2px;
    linkStyle 124 stroke:#FCBC3E,stroke-width:2px;
    linkStyle 125 stroke:#5F84BB,stroke-width:2px;
    linkStyle 126 stroke:#5F84BB,stroke-width:2px;
    linkStyle 127 stroke:#5F84BB,stroke-width:2px;
    linkStyle 128 stroke:#5F84BB,stroke-width:2px;
    linkStyle 129 stroke:#FCBC3E,stroke-width:2px;
    linkStyle 130 stroke:#5F84BB,stroke-width:2px;
    linkStyle 131 stroke:#5F84BB,stroke-width:2px;
    linkStyle 132 stroke:#5F84BB,stroke-width:2px;
    linkStyle 133 stroke:#5F84BB,stroke-width:2px;
    linkStyle 134 stroke:#5F84BB,stroke-width:2px;
    linkStyle 135 stroke:#5F84BB,stroke-width:2px;
    linkStyle 136 stroke:#5F84BB,stroke-width:2px;
    linkStyle 137 stroke:#FCBC3E,stroke-width:2px;
    linkStyle 138 stroke:#5F84BB,stroke-width:2px;
    linkStyle 139 stroke:#5F84BB,stroke-width:2px;
    linkStyle 140 stroke:#5F84BB,stroke-width:2px;
    linkStyle 141 stroke:#5F84BB,stroke-width:2px;
    linkStyle 142 stroke:#5F84BB,stroke-width:2px;
    linkStyle 143 stroke:#FCBC3E,stroke-width:2px;
    linkStyle 144 stroke:#5F84BB,stroke-width:2px;
    linkStyle 145 stroke:#5F84BB,stroke-width:2px;
    linkStyle 146 stroke:#5F84BB,stroke-width:2px;
    linkStyle 147 stroke:#5F84BB,stroke-width:2px;
    linkStyle 148 stroke:#FCBC3E,stroke-width:2px;
    linkStyle 149 stroke:#5F84BB,stroke-width:2px;
    linkStyle 150 stroke:#5F84BB,stroke-width:2px;
    linkStyle 151 stroke:#5F84BB,stroke-width:2px;
    linkStyle 152 stroke:#FCBC3E,stroke-width:2px;
    linkStyle 153 stroke:#5F84BB,stroke-width:2px;
    linkStyle 154 stroke:#5F84BB,stroke-width:2px;
    linkStyle 155 stroke:#5F84BB,stroke-width:2px;
    linkStyle 156 stroke:#5F84BB,stroke-width:2px;
    linkStyle 157 stroke:#5F84BB,stroke-width:2px;
    linkStyle 158 stroke:#5F84BB,stroke-width:2px;
    linkStyle 159 stroke:#5F84BB,stroke-width:2px;
    linkStyle 160 stroke:#5F84BB,stroke-width:2px;
    linkStyle 161 stroke:#FCBC3E,stroke-width:2px;
    linkStyle 162 stroke:#5F84BB,stroke-width:2px;
    linkStyle 163 stroke:#FCBC3E,stroke-width:2px;
    linkStyle 164 stroke:#5F84BB,stroke-width:2px;
    linkStyle 165 stroke:#5F84BB,stroke-width:2px;
    linkStyle 166 stroke:#FCBC3E,stroke-width:2px;
    linkStyle 167 stroke:#5F84BB,stroke-width:2px;
    linkStyle 168 stroke:#FCBC3E,stroke-width:2px;
