flowchart LR
    mtaqacdw1m(("EVAL<br>*mtaqacdw1m*")) --> 8jrbqcts2g("Create MFA Device<br>*8jrbqcts2g*")
    hk00gx2f95(("EVAL<br>*hk00gx2f95*")) --> onogvjusk6("Prompt For OTP<br>*onogvjusk6*")
    qw4n733f3t(("EVAL<br>*qw4n733f3t*")) --> li0d8slgjx("Send email for new device<br>*li0d8slgjx*")
    7jufzmg1rk("Activate MFA Device<br>*7jufzmg1rk*") --> qw4n733f3t(("EVAL<br>*qw4n733f3t*"))
    8jrbqcts2g("Create MFA Device<br>*8jrbqcts2g*") --> hk00gx2f95(("EVAL<br>*hk00gx2f95*"))
    kho2rpwvb7(("EVAL<br>*kho2rpwvb7*")) --> 7jufzmg1rk("Activate MFA Device<br>*7jufzmg1rk*")
    onogvjusk6("Prompt For OTP<br>*onogvjusk6*") --> kho2rpwvb7(("EVAL<br>*kho2rpwvb7*"))
    78i0a08xfl("Send email for threat detection<br>*78i0a08xfl*") --> iz5nper189(("EVAL<br>*iz5nper189*"))
    gsmghrxxoy("Check for KNOWN DEVICE<br>*gsmghrxxoy*") --> nl0cxyid0x(("EVAL<br>*nl0cxyid0x*"))
    99q38lg97t(("EVAL<br>*99q38lg97t*")) --> sqdggkol0g("Go To: Error<br>*sqdggkol0g*")
    iloobtovwh(("EVAL<br>*iloobtovwh*")) --> dxowhkk5n5("Check if Risk Policy ID is empty<br>*dxowhkk5n5*")
    iz5nper189(("EVAL<br>*iz5nper189*")) --> 7hwtzuxjwc("Disable user<br>*7hwtzuxjwc*")
    n69ynlsgag(("EVAL<br>*n69ynlsgag*")) --> nf4hv96sui("Check MFA devices size<br>*nf4hv96sui*")
    cb4rka2li0(("EVAL<br>*cb4rka2li0*")) --> 78i0a08xfl("Send email for threat detection<br>*78i0a08xfl*")
    x8ainlbr6x(("EVAL<br>*x8ainlbr6x*")) --> ndm5er34sv("Risk Score from PingOne Protect<br>*ndm5er34sv*")
    j6salon8z4("Get Values from PingOne Protect analysis<br>*j6salon8z4*") --> cb4rka2li0(("EVAL<br>*cb4rka2li0*"))
    ahjplbui3q("PingOne Notifications<br>*ahjplbui3q*") --> x8ainlbr6x(("EVAL<br>*x8ainlbr6x*"))
    pt24r4nafa(("EVAL<br>*pt24r4nafa*")) --> 3y03qc0kxe("Find user details<br>*3y03qc0kxe*")
    mtaqacdw1m(("EVAL<br>*mtaqacdw1m*")) -- Any Triggers False --> 5231692i67("Return to calling node.<br>*5231692i67*")
    4oyc5l9npk(("EVAL<br>*4oyc5l9npk*")) --> 737gi6ip3e("Go To: PingOne Protect Analysis<br>*737gi6ip3e*")
    u22hch23vs(("EVAL<br>*u22hch23vs*")) --> gsmghrxxoy("Check for KNOWN DEVICE<br>*gsmghrxxoy*")
    zfpuewwuhl("PingOne Protect Analysis<br>*zfpuewwuhl*") --> pt24r4nafa(("EVAL<br>*pt24r4nafa*"))
    3y03qc0kxe("Find user details<br>*3y03qc0kxe*") --> qxdd8mlll5(("EVAL<br>*qxdd8mlll5*"))
    nl0cxyid0x(("EVAL<br>*nl0cxyid0x*")) -- Any Triggers False --> ahjplbui3q("PingOne Notifications<br>*ahjplbui3q*")
    li0d8slgjx("Send email for new device<br>*li0d8slgjx*") --> e3httj56zd(("EVAL<br>*e3httj56zd*"))
    737gi6ip3e("Go To: PingOne Protect Analysis<br>*737gi6ip3e*") --> 9vk797lpxx(("EVAL<br>*9vk797lpxx*"))
    nf4hv96sui("Check MFA devices size<br>*nf4hv96sui*") --> mtaqacdw1m(("EVAL<br>*mtaqacdw1m*"))
    1cbcpbc5no(("EVAL<br>*1cbcpbc5no*")) --> 4psx471uwp("Authentication Required<br>*4psx471uwp*")
    h8dtvwld36(("EVAL<br>*h8dtvwld36*")) --> 76reddil11("Go To: FIDO2<br>*76reddil11*")
    r0hto2xun7("Present OTP Form<br>*r0hto2xun7*") --> l5z3ngnhjv(("EVAL<br>*l5z3ngnhjv*"))
    1gtc5d0awz(("EVAL<br>*1gtc5d0awz*")) --> kok73n8hkt("Go To: OTP<br>*kok73n8hkt*")
    4psx471uwp("Authentication Required<br>*4psx471uwp*") --> 1gtc5d0awz(("EVAL<br>*1gtc5d0awz*"))
    qurffyxc2d("Split by user selection <br>*qurffyxc2d*") --> gsw5wwtm7t(("EVAL<br>*gsw5wwtm7t*"))
    en7y953x31("Get authMethod Value<br>*en7y953x31*") --> 0w6twuixxq(("EVAL<br>*0w6twuixxq*"))
    fzjj3nuh7m(("EVAL<br>*fzjj3nuh7m*")) -- Any Triggers False --> dxsjn36392("Go To: Error<br>*dxsjn36392*")
    mt9kvt7hnn(("EVAL<br>*mt9kvt7hnn*")) --> fgc8woctfo("Validate Passcode<br>*fgc8woctfo*")
    qurffyxc2d("Split by user selection <br>*qurffyxc2d*") --> 00j11fkhbx(("EVAL<br>*00j11fkhbx*"))
    fzjj3nuh7m(("EVAL<br>*fzjj3nuh7m*")) --> uz6hhdt9gv("OTP Resent Message<br>*uz6hhdt9gv*")
    zxfluj3oxa("OTP<br>*zxfluj3oxa*") --> b0csz8cgnl(("EVAL<br>*b0csz8cgnl*"))
    qurffyxc2d("Split by user selection <br>*qurffyxc2d*") --> ig2ndq8bf2(("EVAL<br>*ig2ndq8bf2*"))
    00j11fkhbx(("EVAL<br>*00j11fkhbx*")) --> beakf43h8t("Go To: Device Selection<br>*beakf43h8t*")
    gsw5wwtm7t(("EVAL<br>*gsw5wwtm7t*")) --> r6lnkuy0yh("Transform Passcode To Lowercase<br>*r6lnkuy0yh*")
    ig2ndq8bf2(("EVAL<br>*ig2ndq8bf2*")) --> m1e0cw0ygl("Resend OTP<br>*m1e0cw0ygl*")
    m1e0cw0ygl("Resend OTP<br>*m1e0cw0ygl*") --> fzjj3nuh7m(("EVAL<br>*fzjj3nuh7m*"))
    r6lnkuy0yh("Transform Passcode To Lowercase<br>*r6lnkuy0yh*") --> mt9kvt7hnn(("EVAL<br>*mt9kvt7hnn*"))
    hdc8oa72ci("Is invalidOTP Error<br>*hdc8oa72ci*") --> 8h5tjkrug9(("EVAL<br>*8h5tjkrug9*"))
    v97rmwpban(("EVAL<br>*v97rmwpban*")) --> 5pixttpidw("Invalid Passcode Error<br>*5pixttpidw*")
    gntsn38l9s("CIAM - Magic Link Authentication<br>*gntsn38l9s*") --> 51zazld6jz(("EVAL<br>*51zazld6jz*"))
    5uyrxkfgza(("EVAL<br>*5uyrxkfgza*")) --> tidk1pmqix("Return Success Response<br>*tidk1pmqix*")
    8h5tjkrug9(("EVAL<br>*8h5tjkrug9*")) --> mmojm56jlj("Go To: Error<br>*mmojm56jlj*")
    uoyh9kzwil("Device Selection<br>*uoyh9kzwil*") --> bhgtvbjvu1(("EVAL<br>*bhgtvbjvu1*"))
    se271xaurx(("EVAL<br>*se271xaurx*")) -- Any Triggers False --> uwfrx6s60u("Go To: Error<br>*uwfrx6s60u*")
    vr1msssq3l(("EVAL<br>*vr1msssq3l*")) --> wpbqyomp7z("Go To: Success <br>*wpbqyomp7z*")
    wa07p8s7qm("Not Magic Link?<br>*wa07p8s7qm*") --> vr1msssq3l(("EVAL<br>*vr1msssq3l*"))
    vul5k2q2dw(("EVAL<br>*vul5k2q2dw*")) --> te0bcdks99("Magic Link Authentication<br>*te0bcdks99*")
    wa07p8s7qm("Not Magic Link?<br>*wa07p8s7qm*") --> vul5k2q2dw(("EVAL<br>*vul5k2q2dw*"))
    imhudhsy1w(("EVAL<br>*imhudhsy1w*")) --> e717up82dy("Device Selected By The User<br>*e717up82dy*")
    wa07p8s7qm("Not Magic Link?<br>*wa07p8s7qm*") --> imhudhsy1w(("EVAL<br>*imhudhsy1w*"))
    j8lmuiytzs("Is MFA Enabled?<br>*j8lmuiytzs*") --> bf9jlbogz1(("EVAL<br>*bf9jlbogz1*"))
    bhgtvbjvu1(("EVAL<br>*bhgtvbjvu1*")) --> 1qtib8s0uu("Select Authentication Device<br>*1qtib8s0uu*")
    0sua91hqk7(("EVAL<br>*0sua91hqk7*")) --> 10oaokas61("Start MFA Authentication<br>*10oaokas61*")
    845xzgf4bk(("EVAL<br>*845xzgf4bk*")) -- Any Triggers False --> ulsqznx6ut("Is Constraint Violation Error<br>*ulsqznx6ut*")
    51zazld6jz(("EVAL<br>*51zazld6jz*")) --> 5gs9h0ar04("Go To: Success <br>*5gs9h0ar04*")
    3a77bpgwom(("EVAL<br>*3a77bpgwom*")) --> y7f8x8dkw2("Go To: Error<br>*y7f8x8dkw2*")
    zfsjjfa5h6("Present FIDO2 Form <br>*zfsjjfa5h6*") --> 9pb86bg0qi(("EVAL<br>*9pb86bg0qi*"))
    wf0h6fo6h8("Split By Users Selection<br>*wf0h6fo6h8*") --> ay2mm4z4xe(("EVAL<br>*ay2mm4z4xe*"))
    ulsqznx6ut("Is Constraint Violation Error<br>*ulsqznx6ut*") --> fu06ckn12l(("EVAL<br>*fu06ckn12l*"))
    fj8w62y4z3("Assert FIDO Device Authentication<br>*fj8w62y4z3*") --> 845xzgf4bk(("EVAL<br>*845xzgf4bk*"))
    fu06ckn12l(("EVAL<br>*fu06ckn12l*")) --> y8pxpynfle("Invalid Device Error<br>*y8pxpynfle*")
    7vrrd3uuhm(("EVAL<br>*7vrrd3uuhm*")) --> en7y953x31("Get authMethod Value<br>*en7y953x31*")
    1lam7h7jbc("Split By Subflows Result<br>*1lam7h7jbc*") --> 9fzm9oj8fd(("EVAL<br>*9fzm9oj8fd*"))
    qsu3efxcsp(("EVAL<br>*qsu3efxcsp*")) --> 1lam7h7jbc("Split By Subflows Result<br>*1lam7h7jbc*")
    6yu5p2iz3r(("EVAL<br>*6yu5p2iz3r*")) --> ms19ql02hi("Get MFA Status<br>*ms19ql02hi*")
    en7y953x31("Get authMethod Value<br>*en7y953x31*") --> 0w6twuixxq(("EVAL<br>*0w6twuixxq*"))
    t6p5s6t603("Get WebAuthn Browser Compatibility<br>*t6p5s6t603*") --> 4oyc5l9npk(("EVAL<br>*4oyc5l9npk*"))
    10uwd1ccc4("Filter Unusable Devices<br>*10uwd1ccc4*") --> se271xaurx(("EVAL<br>*se271xaurx*"))
    wzzac3ucto("Create Masked Devices<br>*wzzac3ucto*") --> 6yu5p2iz3r(("EVAL<br>*6yu5p2iz3r*"))
    fd7o3icva4(("EVAL<br>*fd7o3icva4*")) --> j8lmuiytzs("Is MFA Enabled?<br>*j8lmuiytzs*")
    ms19ql02hi("Get MFA Status<br>*ms19ql02hi*") --> fd7o3icva4(("EVAL<br>*fd7o3icva4*"))
    3nn0mw8jkt(("EVAL<br>*3nn0mw8jkt*")) --> 61c9e2dt59("Go To: Device Selection<br>*61c9e2dt59*")
    51zazld6jz(("EVAL<br>*51zazld6jz*")) -- Any Triggers False --> nvxwg0vum3("Go To: Error<br>*nvxwg0vum3*")
    9fzm9oj8fd(("EVAL<br>*9fzm9oj8fd*")) --> lgn9kliiqj("Go To: Success <br>*lgn9kliiqj*")
    b0csz8cgnl(("EVAL<br>*b0csz8cgnl*")) --> fq7l0s8w2s("Mask Device<br>*fq7l0s8w2s*")
    1lam7h7jbc("Split By Subflows Result<br>*1lam7h7jbc*") --> lylme68jbw(("EVAL<br>*lylme68jbw*"))
    0w6twuixxq(("EVAL<br>*0w6twuixxq*")) --> 5sb0db3vb0("Go To: Success <br>*5sb0db3vb0*")
    7vpjww2ek2("FIDO2<br>*7vpjww2ek2*") --> t04dles3gs(("EVAL<br>*t04dles3gs*"))
    9vk797lpxx(("EVAL<br>*9vk797lpxx*")) --> 10uwd1ccc4("Filter Unusable Devices<br>*10uwd1ccc4*")
    wf0h6fo6h8("Split By Users Selection<br>*wf0h6fo6h8*") --> 3nn0mw8jkt(("EVAL<br>*3nn0mw8jkt*"))
    k46n95w9eo("Success <br>*k46n95w9eo*") --> 5uyrxkfgza(("EVAL<br>*5uyrxkfgza*"))
    hdc8oa72ci("Is invalidOTP Error<br>*hdc8oa72ci*") --> v97rmwpban(("EVAL<br>*v97rmwpban*"))
    7vrrd3uuhm(("EVAL<br>*7vrrd3uuhm*")) -- Any Triggers False --> hdc8oa72ci("Is invalidOTP Error<br>*hdc8oa72ci*")
    fgc8woctfo("Validate Passcode<br>*fgc8woctfo*") --> 7vrrd3uuhm(("EVAL<br>*7vrrd3uuhm*"))
    zbhvblc83s("Authentication Method Selection<br>*zbhvblc83s*") --> ybwxgols9w(("EVAL<br>*ybwxgols9w*"))
    4psx471uwp("Authentication Required<br>*4psx471uwp*") --> h8dtvwld36(("EVAL<br>*h8dtvwld36*"))
    ybwxgols9w(("EVAL<br>*ybwxgols9w*")) --> 9zctbmveoc("Enrich Device Details<br>*9zctbmveoc*")
    iloobtovwh(("EVAL<br>*iloobtovwh*")) --> dwhgyxkavz("Error Error Response<br>*dwhgyxkavz*")
    qsu3efxcsp(("EVAL<br>*qsu3efxcsp*")) -- Any Triggers False --> muund54c7j("Go To: Error<br>*muund54c7j*")
    6p4frzqpp1("Get Origin<br>*6p4frzqpp1*") --> sk7vd2o3r7(("EVAL<br>*sk7vd2o3r7*"))
    845xzgf4bk(("EVAL<br>*845xzgf4bk*")) --> dp43hy7h76("Get authMethod Value<br>*dp43hy7h76*")
    5v1i2f1az4(("EVAL<br>*5v1i2f1az4*")) -- Any Triggers False --> cbapcifpyy("Go To: Error<br>*cbapcifpyy*")
    nydopq0ve3(("EVAL<br>*nydopq0ve3*")) -- Any Triggers False --> qzuk2c4cdb("Go To: Error<br>*qzuk2c4cdb*")
    nydopq0ve3(("EVAL<br>*nydopq0ve3*")) --> t6p5s6t603("Get WebAuthn Browser Compatibility<br>*t6p5s6t603*")
    fq7l0s8w2s("Mask Device<br>*fq7l0s8w2s*") --> bdjeulfdki(("EVAL<br>*bdjeulfdki*"))
    jd87iaho99("Error<br>*jd87iaho99*") --> iloobtovwh(("EVAL<br>*iloobtovwh*"))
    7vz1yqkdqo(("EVAL<br>*7vz1yqkdqo*")) --> gntsn38l9s("CIAM - Magic Link Authentication<br>*gntsn38l9s*")
    bdjeulfdki(("EVAL<br>*bdjeulfdki*")) --> r0hto2xun7("Present OTP Form<br>*r0hto2xun7*")
    9m5a2f4emp("Get Users Existing Devices<br>*9m5a2f4emp*") --> nydopq0ve3(("EVAL<br>*nydopq0ve3*"))
    dp43hy7h76("Get authMethod Value<br>*dp43hy7h76*") --> zep1ojf98g(("EVAL<br>*zep1ojf98g*"))
    czzrbt1dsb("Magic Link Enabled<br>*czzrbt1dsb*") --> 7vz1yqkdqo(("EVAL<br>*7vz1yqkdqo*"))
    ulsqznx6ut("Is Constraint Violation Error<br>*ulsqznx6ut*") --> 3a77bpgwom(("EVAL<br>*3a77bpgwom*"))
    ay2mm4z4xe(("EVAL<br>*ay2mm4z4xe*")) --> fj8w62y4z3("Assert FIDO Device Authentication<br>*fj8w62y4z3*")
    0sua91hqk7(("EVAL<br>*0sua91hqk7*")) -- Any Triggers False --> czzrbt1dsb("Magic Link Enabled<br>*czzrbt1dsb*")
    sk7vd2o3r7(("EVAL<br>*sk7vd2o3r7*")) --> 9m5a2f4emp("Get Users Existing Devices<br>*9m5a2f4emp*")
    lylme68jbw(("EVAL<br>*lylme68jbw*")) --> fkkub10ukt("Go To: Device Selection<br>*fkkub10ukt*")
    zep1ojf98g(("EVAL<br>*zep1ojf98g*")) --> 9f0dokmcu9("Go To: Success <br>*9f0dokmcu9*")
    10oaokas61("Start MFA Authentication<br>*10oaokas61*") --> 4l39ap532m(("EVAL<br>*4l39ap532m*"))
    47qta86y95(("EVAL<br>*47qta86y95*")) -- Any Triggers False --> x0jx5r2pyd("Go To: Error<br>*x0jx5r2pyd*")
    frh74jp1jg("Only One Usable Device<br>*frh74jp1jg*") --> ydyrhm9fkz(("EVAL<br>*ydyrhm9fkz*"))
    47qta86y95(("EVAL<br>*47qta86y95*")) --> wphj1fy8ri("Go To: Authentication Method Selection<br>*wphj1fy8ri*")
    b01n00fwkm("Continue MFA With Only Device<br>*b01n00fwkm*") --> 47qta86y95(("EVAL<br>*47qta86y95*"))
    7vz1yqkdqo(("EVAL<br>*7vz1yqkdqo*")) -- Any Triggers False --> 2uhj1oobbe("Go To: Error<br>*2uhj1oobbe*")
    4l39ap532m(("EVAL<br>*4l39ap532m*")) --> icy7kw57ll("Authentication Prompt<br>*icy7kw57ll*")
    icy7kw57ll("Authentication Prompt<br>*icy7kw57ll*") --> v0t14r4lv2(("EVAL<br>*v0t14r4lv2*"))
    v0t14r4lv2(("EVAL<br>*v0t14r4lv2*")) --> frh74jp1jg("Only One Usable Device<br>*frh74jp1jg*")
    4l39ap532m(("EVAL<br>*4l39ap532m*")) -- Any Triggers False --> t4cuk82upd("Go To: Error<br>*t4cuk82upd*")
    icy7kw57ll("Authentication Prompt<br>*icy7kw57ll*") --> wj5284rjb8(("EVAL<br>*wj5284rjb8*"))
    wj5284rjb8(("EVAL<br>*wj5284rjb8*")) --> l7i5qjffz1("Go To: Authentication Method Selection<br>*l7i5qjffz1*")
    icy7kw57ll("Authentication Prompt<br>*icy7kw57ll*") --> vw8zbuzgod(("EVAL<br>*vw8zbuzgod*"))
    vw8zbuzgod(("EVAL<br>*vw8zbuzgod*")) --> j55n69o5i7("Go To: Authentication Method Selection<br>*j55n69o5i7*")
    ydyrhm9fkz(("EVAL<br>*ydyrhm9fkz*")) -- Any Triggers False --> a58tdqlgfb("Go To: Device Selection<br>*a58tdqlgfb*")
    t04dles3gs(("EVAL<br>*t04dles3gs*")) --> zfsjjfa5h6("Present FIDO2 Form <br>*zfsjjfa5h6*")
    5v1i2f1az4(("EVAL<br>*5v1i2f1az4*")) --> 4vf8sqyl70("Go To: Authentication Method Selection<br>*4vf8sqyl70*")
    9pb86bg0qi(("EVAL<br>*9pb86bg0qi*")) --> wf0h6fo6h8("Split By Users Selection<br>*wf0h6fo6h8*")
    1qtib8s0uu("Select Authentication Device<br>*1qtib8s0uu*") --> iagfrg0an6(("EVAL<br>*iagfrg0an6*"))
    e717up82dy("Device Selected By The User<br>*e717up82dy*") --> 5v1i2f1az4(("EVAL<br>*5v1i2f1az4*"))
    bf9jlbogz1(("EVAL<br>*bf9jlbogz1*")) --> 2n3az4vori("User Has Active Devices<br>*2n3az4vori*")
    iagfrg0an6(("EVAL<br>*iagfrg0an6*")) --> wa07p8s7qm("Not Magic Link?<br>*wa07p8s7qm*")
    bf9jlbogz1(("EVAL<br>*bf9jlbogz1*")) -- Any Triggers False --> czzrbt1dsb("Magic Link Enabled<br>*czzrbt1dsb*")
    2n3az4vori("User Has Active Devices<br>*2n3az4vori*") --> 0sua91hqk7(("EVAL<br>*0sua91hqk7*"))
    te0bcdks99("Magic Link Authentication<br>*te0bcdks99*") --> qsu3efxcsp(("EVAL<br>*qsu3efxcsp*"))
    ydyrhm9fkz(("EVAL<br>*ydyrhm9fkz*")) --> xsm25p5qf7("Magic Link Enabled<br>*xsm25p5qf7*")
    xsm25p5qf7("Magic Link Enabled<br>*xsm25p5qf7*") --> ayodtok1lb(("EVAL<br>*ayodtok1lb*"))
    ayodtok1lb(("EVAL<br>*ayodtok1lb*")) --> x9k0uusly8("Go To: Device Selection<br>*x9k0uusly8*")
    ayodtok1lb(("EVAL<br>*ayodtok1lb*")) -- Any Triggers False --> b01n00fwkm("Continue MFA With Only Device<br>*b01n00fwkm*")
    9zctbmveoc("Enrich Device Details<br>*9zctbmveoc*") --> 1cbcpbc5no(("EVAL<br>*1cbcpbc5no*"))
    l5z3ngnhjv(("EVAL<br>*l5z3ngnhjv*")) --> qurffyxc2d("Split by user selection <br>*qurffyxc2d*")
    se271xaurx(("EVAL<br>*se271xaurx*")) --> wzzac3ucto("Create Masked Devices<br>*wzzac3ucto*")
    sk3dza5671(("EVAL<br>*sk3dza5671*")) --> di86a7q7j0("Go To: Error<br>*di86a7q7j0*")
    e3httj56zd(("EVAL<br>*e3httj56zd*")) -- Any Triggers False --> 5231692i67("Return to calling node.<br>*5231692i67*")
    qxdd8mlll5(("EVAL<br>*qxdd8mlll5*")) --> u9ab712lfx("Invoke PingOne Protect subflow<br>*u9ab712lfx*")
    u9ab712lfx("Invoke PingOne Protect subflow<br>*u9ab712lfx*") --> vexxoicu6a(("EVAL<br>*vexxoicu6a*"))
    vexxoicu6a(("EVAL<br>*vexxoicu6a*")) --> 3s5kidc2wc("Get Values from PingOne Protect analysis<br>*3s5kidc2wc*")
    vexxoicu6a(("EVAL<br>*vexxoicu6a*")) -- Any Triggers False --> j6salon8z4("Get Values from PingOne Protect analysis<br>*j6salon8z4*")
    3s5kidc2wc("Get Values from PingOne Protect analysis<br>*3s5kidc2wc*") --> u22hch23vs(("EVAL<br>*u22hch23vs*"))
    nl0cxyid0x(("EVAL<br>*nl0cxyid0x*")) --> ndm5er34sv("Risk Score from PingOne Protect<br>*ndm5er34sv*")
    ndm5er34sv("Risk Score from PingOne Protect<br>*ndm5er34sv*") --> 4n12f0orqv(("EVAL<br>*4n12f0orqv*"))
    4n12f0orqv(("EVAL<br>*4n12f0orqv*")) --> d2uumx5mpk("Return to calling node<br>*d2uumx5mpk*")
    ndm5er34sv("Risk Score from PingOne Protect<br>*ndm5er34sv*") --> n69ynlsgag(("EVAL<br>*n69ynlsgag*"))
    7hwtzuxjwc("Disable user<br>*7hwtzuxjwc*") --> 99q38lg97t(("EVAL<br>*99q38lg97t*"))
    ndm5er34sv("Risk Score from PingOne Protect<br>*ndm5er34sv*") --> sk3dza5671(("EVAL<br>*sk3dza5671*"))
    kgxiu8h9i5(("EVAL<br>*kgxiu8h9i5*")) --> 9w2fwmdjtp("PingOne Protect Risk ID is Empty/NULL<br>*9w2fwmdjtp*")
    qw4n733f3t(("EVAL<br>*qw4n733f3t*")) -- Any Triggers False --> sj6aezm25b("Go To: Error<br>*sj6aezm25b*")
    dxowhkk5n5("Check if Risk Policy ID is empty<br>*dxowhkk5n5*") --> kgxiu8h9i5(("EVAL<br>*kgxiu8h9i5*"))
    kgxiu8h9i5(("EVAL<br>*kgxiu8h9i5*")) -- Any Triggers False --> p3914imkz7("Update Risk Evaluation - FAILURE<br>*p3914imkz7*")
    5uyrxkfgza(("EVAL<br>*5uyrxkfgza*")) --> wi6hu0ai62("Check if Risk Policy ID is empty<br>*wi6hu0ai62*")
    wi6hu0ai62("Check if Risk Policy ID is empty<br>*wi6hu0ai62*") --> 33jpsgsdxv(("EVAL<br>*33jpsgsdxv*"))
    33jpsgsdxv(("EVAL<br>*33jpsgsdxv*")) -- Any Triggers False --> ilu6o9n2x7("Update Risk Evaluation - SUCCESS<br>*ilu6o9n2x7*")
    33jpsgsdxv(("EVAL<br>*33jpsgsdxv*")) --> 33kryo3flh("PingOne Protect Risk ID is Empty/NULL<br>*33kryo3flh*")
    fd7o3icva4(("EVAL<br>*fd7o3icva4*")) -- Any Triggers False --> 9q9zj5ndao("Go To: Error<br>*9q9zj5ndao*")

