flowchart LR
    ali9zum89s(("EVAL<br>*ali9zum89s*")) -- Any False --> gy5df5u07u("Go To: Error<br>*gy5df5u07u*")
    zsk0ny89ud("Create Magic Link<br>*zsk0ny89ud*") -- All True --> 65s242z206(("EVAL<br>*65s242z206*"))
    w9wzxxn1e0("Magic Link Form<br>*w9wzxxn1e0*") -- All True --> m2p5qnib8n(("EVAL<br>*m2p5qnib8n*"))
    ali9zum89s(("EVAL<br>*ali9zum89s*")) -- All True --> fhoue68esb("Magic Link Polling<br>*fhoue68esb*")
    65s242z206(("EVAL<br>*65s242z206*")) -- All True --> fetjewgnk5("Send Magic Link Email<br>*fetjewgnk5*")
    g1fs3uznfh(("EVAL<br>*g1fs3uznfh*")) -- All True --> cb5wbngwml("Return Error Response<br>*cb5wbngwml*")
    3ma220y2v8(("EVAL<br>*3ma220y2v8*")) -- All True --> i8unidj14v("Go To: Success <br>*i8unidj14v*")
    z86jockb1t("Split By Users Selection <br>*z86jockb1t*") -- All True --> zv9k30dslp(("EVAL<br>*zv9k30dslp*"))
    hhwhmetaid("Continue Out of Band<br>*hhwhmetaid*") -- All True --> ln2n5kqqb8(("EVAL<br>*ln2n5kqqb8*"))
    fhoue68esb("Magic Link Polling<br>*fhoue68esb*") -- All True --> 2ynekjzhbj(("EVAL<br>*2ynekjzhbj*"))
    2ynekjzhbj(("EVAL<br>*2ynekjzhbj*")) -- All True --> z80t8d8glj("Check Challenge Status<br>*z80t8d8glj*")
    fetjewgnk5("Send Magic Link Email<br>*fetjewgnk5*") -- All True --> ali9zum89s(("EVAL<br>*ali9zum89s*"))
    jdrbqfg1mz("Is Challenge Not Expired?<br>*jdrbqfg1mz*") -- All True --> v0rkta2j1x(("EVAL<br>*v0rkta2j1x*"))
    qvn5tw6kbc("Is Challenge Approved?<br>*qvn5tw6kbc*") -- All True --> 3ma220y2v8(("EVAL<br>*3ma220y2v8*"))
    si1p71skgq("Deny Challenge After Expiration<br>*si1p71skgq*") -- All True --> rbbahd8wkk(("EVAL<br>*rbbahd8wkk*"))
    z86jockb1t("Split By Users Selection <br>*z86jockb1t*") -- All True --> 4ry973ap9g(("EVAL<br>*4ry973ap9g*"))
    3ma220y2v8(("EVAL<br>*3ma220y2v8*")) -- Any False --> si1p71skgq("Deny Challenge After Expiration<br>*si1p71skgq*")
    rbbahd8wkk(("EVAL<br>*rbbahd8wkk*")) -- Any False --> 2nagahrwxs("Go To: Error<br>*2nagahrwxs*")
    m2p5qnib8n(("EVAL<br>*m2p5qnib8n*")) -- All True --> z86jockb1t("Split By Users Selection <br>*z86jockb1t*")
    v0rkta2j1x(("EVAL<br>*v0rkta2j1x*")) -- All True --> ebtd5fr0tn("Approve Challenge Status<br>*ebtd5fr0tn*")
    exmvyabfps("Check Challenge Status<br>*exmvyabfps*") -- All True --> 9rfeo7c8cp(("EVAL<br>*9rfeo7c8cp*"))
    ln2n5kqqb8(("EVAL<br>*ln2n5kqqb8*")) -- All True --> exmvyabfps("Check Challenge Status<br>*exmvyabfps*")
    v0rkta2j1x(("EVAL<br>*v0rkta2j1x*")) -- Any False --> utjcbphp35("Show Expiration Error<br>*utjcbphp35*")
    9rfeo7c8cp(("EVAL<br>*9rfeo7c8cp*")) -- All True --> jdrbqfg1mz("Is Challenge Not Expired?<br>*jdrbqfg1mz*")
    qcxgcbyy02(("EVAL<br>*qcxgcbyy02*")) -- Any False --> 31jujh5ubp("Go To: Error<br>*31jujh5ubp*")
    qcxgcbyy02(("EVAL<br>*qcxgcbyy02*")) -- All True --> qvn5tw6kbc("Is Challenge Approved?<br>*qvn5tw6kbc*")
    4ry973ap9g(("EVAL<br>*4ry973ap9g*")) -- All True --> i57cwf2jh5("Go To: Success <br>*i57cwf2jh5*")
    v9e53rljmv("Success <br>*v9e53rljmv*") -- All True --> r20nxc61oc(("EVAL<br>*r20nxc61oc*"))
    ebtd5fr0tn("Approve Challenge Status<br>*ebtd5fr0tn*") -- All True --> drn0tajuo1(("EVAL<br>*drn0tajuo1*"))
    c9rl5wctez("Error<br>*c9rl5wctez*") -- All True --> g1fs3uznfh(("EVAL<br>*g1fs3uznfh*"))
    z80t8d8glj("Check Challenge Status<br>*z80t8d8glj*") -- All True --> qcxgcbyy02(("EVAL<br>*qcxgcbyy02*"))
    drn0tajuo1(("EVAL<br>*drn0tajuo1*")) -- All True --> footoj1rr5("Success Message<br>*footoj1rr5*")
    r20nxc61oc(("EVAL<br>*r20nxc61oc*")) -- All True --> 6pm68xyuuo("Return Success Response<br>*6pm68xyuuo*")
    p5i7v1wl02(("EVAL<br>*p5i7v1wl02*")) -- All True --> w9wzxxn1e0("Magic Link Form<br>*w9wzxxn1e0*")
    n6qy3v9bsy("Find User<br>*n6qy3v9bsy*") -- All True --> p5i7v1wl02(("EVAL<br>*p5i7v1wl02*"))
    zv9k30dslp(("EVAL<br>*zv9k30dslp*")) -- All True --> zsk0ny89ud("Create Magic Link<br>*zsk0ny89ud*")
    zv9k30dslp(("EVAL<br>*zv9k30dslp*")) -- All True --> hhwhmetaid("Continue Out of Band<br>*hhwhmetaid*")
    p5i7v1wl02(("EVAL<br>*p5i7v1wl02*")) -- Any False --> u5xirin76g("Go To: Error<br>*u5xirin76g*")

    linkStyle 0 stroke:#FCBC3E,stroke-width:2px;
    linkStyle 1 stroke:#5F84BB,stroke-width:2px;
    linkStyle 2 stroke:#5F84BB,stroke-width:2px;
    linkStyle 3 stroke:#5F84BB,stroke-width:2px;
    linkStyle 4 stroke:#5F84BB,stroke-width:2px;
    linkStyle 5 stroke:#5F84BB,stroke-width:2px;
    linkStyle 6 stroke:#5F84BB,stroke-width:2px;
    linkStyle 7 stroke:#5F84BB,stroke-width:2px;
    linkStyle 8 stroke:#5F84BB,stroke-width:2px;
    linkStyle 9 stroke:#5F84BB,stroke-width:2px;
    linkStyle 10 stroke:#5F84BB,stroke-width:2px;
    linkStyle 11 stroke:#5F84BB,stroke-width:2px;
    linkStyle 12 stroke:#5F84BB,stroke-width:2px;
    linkStyle 13 stroke:#5F84BB,stroke-width:2px;
    linkStyle 14 stroke:#5F84BB,stroke-width:2px;
    linkStyle 15 stroke:#5F84BB,stroke-width:2px;
    linkStyle 16 stroke:#FCBC3E,stroke-width:2px;
    linkStyle 17 stroke:#FCBC3E,stroke-width:2px;
    linkStyle 18 stroke:#5F84BB,stroke-width:2px;
    linkStyle 19 stroke:#5F84BB,stroke-width:2px;
    linkStyle 20 stroke:#5F84BB,stroke-width:2px;
    linkStyle 21 stroke:#5F84BB,stroke-width:2px;
    linkStyle 22 stroke:#FCBC3E,stroke-width:2px;
    linkStyle 23 stroke:#5F84BB,stroke-width:2px;
    linkStyle 24 stroke:#FCBC3E,stroke-width:2px;
    linkStyle 25 stroke:#5F84BB,stroke-width:2px;
    linkStyle 26 stroke:#5F84BB,stroke-width:2px;
    linkStyle 27 stroke:#5F84BB,stroke-width:2px;
    linkStyle 28 stroke:#5F84BB,stroke-width:2px;
    linkStyle 29 stroke:#5F84BB,stroke-width:2px;
    linkStyle 30 stroke:#5F84BB,stroke-width:2px;
    linkStyle 31 stroke:#5F84BB,stroke-width:2px;
    linkStyle 32 stroke:#5F84BB,stroke-width:2px;
    linkStyle 33 stroke:#5F84BB,stroke-width:2px;
    linkStyle 34 stroke:#5F84BB,stroke-width:2px;
    linkStyle 35 stroke:#5F84BB,stroke-width:2px;
    linkStyle 36 stroke:#5F84BB,stroke-width:2px;
    linkStyle 37 stroke:#FCBC3E,stroke-width:2px;
