flowchart LR
    r8sc175hhf(("EVAL<br>*r8sc175hhf*")) -- All True --> wweoq86mfw("Return Success Response<br>*wweoq86mfw*")
    hpve55zazv(("EVAL<br>*hpve55zazv*")) -- Any False --> gf3bwis6oi("Go To: Error<br>*gf3bwis6oi*")
    ru45xolut1(("EVAL<br>*ru45xolut1*")) -- All True --> 5d5o5ia81u("Is Validation Limit Reached?<br>*5d5o5ia81u*")
    rjau0njx5i("Form Button Check<br>*rjau0njx5i*") -- All True --> t92nqcnwux(("EVAL<br>*t92nqcnwux*"))
    rjau0njx5i("Form Button Check<br>*rjau0njx5i*") -- All True --> n5icn97kyh(("EVAL<br>*n5icn97kyh*"))
    8l8a54vefk(("EVAL<br>*8l8a54vefk*")) -- Any False --> ab91zkjrgx("Go To: Error<br>*ab91zkjrgx*")
    hpve55zazv(("EVAL<br>*hpve55zazv*")) -- All True --> 1vyzcyazgf("Validate verification code<br>*1vyzcyazgf*")
    sju60xf677(("EVAL<br>*sju60xf677*")) -- All True --> rjau0njx5i("Form Button Check<br>*rjau0njx5i*")
    8l8a54vefk(("EVAL<br>*8l8a54vefk*")) -- All True --> 527m4tr2s2("Verification Code Resent<br>*527m4tr2s2*")
    n5icn97kyh(("EVAL<br>*n5icn97kyh*")) -- All True --> 9lrqw38492("Resend Verification Code<br>*9lrqw38492*")
    xsb00g2t92("Set Validation Attempt To Zero<br>*xsb00g2t92*") -- All True --> qskpbqg2yf(("EVAL<br>*qskpbqg2yf*"))
    qskpbqg2yf(("EVAL<br>*qskpbqg2yf*")) -- All True --> s5yykzv8zd("Prompt For Verification Code<br>*s5yykzv8zd*")
    5d5o5ia81u("Is Validation Limit Reached?<br>*5d5o5ia81u*") -- All True --> hpve55zazv(("EVAL<br>*hpve55zazv*"))
    r8sc175hhf(("EVAL<br>*r8sc175hhf*")) -- Any False --> 8gqiq4sagn("Could not validate the verification code<br>*8gqiq4sagn*")
    t92nqcnwux(("EVAL<br>*t92nqcnwux*")) -- All True --> wfe8dz7k7v("Increment Validation Attempt<br>*wfe8dz7k7v*")
    1vyzcyazgf("Validate verification code<br>*1vyzcyazgf*") -- All True --> r8sc175hhf(("EVAL<br>*r8sc175hhf*"))
    wfe8dz7k7v("Increment Validation Attempt<br>*wfe8dz7k7v*") -- All True --> ru45xolut1(("EVAL<br>*ru45xolut1*"))
    9lrqw38492("Resend Verification Code<br>*9lrqw38492*") -- All True --> 8l8a54vefk(("EVAL<br>*8l8a54vefk*"))
    s5yykzv8zd("Prompt For Verification Code<br>*s5yykzv8zd*") -- All True --> sju60xf677(("EVAL<br>*sju60xf677*"))
    xbvfnq8o31("Error<br>*xbvfnq8o31*") -- All True --> 90g8cf6l2u(("EVAL<br>*90g8cf6l2u*"))
    90g8cf6l2u(("EVAL<br>*90g8cf6l2u*")) -- All True --> rfo66ayuok("Return Error Response<br>*rfo66ayuok*")

    linkStyle 0 stroke:#5F84BB,stroke-width:2px;
    linkStyle 1 stroke:#FCBC3E,stroke-width:2px;
    linkStyle 2 stroke:#5F84BB,stroke-width:2px;
    linkStyle 3 stroke:#5F84BB,stroke-width:2px;
    linkStyle 4 stroke:#5F84BB,stroke-width:2px;
    linkStyle 5 stroke:#FCBC3E,stroke-width:2px;
    linkStyle 6 stroke:#5F84BB,stroke-width:2px;
    linkStyle 7 stroke:#5F84BB,stroke-width:2px;
    linkStyle 8 stroke:#5F84BB,stroke-width:2px;
    linkStyle 9 stroke:#5F84BB,stroke-width:2px;
    linkStyle 10 stroke:#5F84BB,stroke-width:2px;
    linkStyle 11 stroke:#5F84BB,stroke-width:2px;
    linkStyle 12 stroke:#5F84BB,stroke-width:2px;
    linkStyle 13 stroke:#FCBC3E,stroke-width:2px;
    linkStyle 14 stroke:#5F84BB,stroke-width:2px;
    linkStyle 15 stroke:#5F84BB,stroke-width:2px;
    linkStyle 16 stroke:#5F84BB,stroke-width:2px;
    linkStyle 17 stroke:#5F84BB,stroke-width:2px;
    linkStyle 18 stroke:#5F84BB,stroke-width:2px;
    linkStyle 19 stroke:#5F84BB,stroke-width:2px;
    linkStyle 20 stroke:#5F84BB,stroke-width:2px;
