flowchart LR
    r8sc175hhf(("EVAL<br>*r8sc175hhf*")) --> wweoq86mfw("Return Success Response<br>*wweoq86mfw*")
    hpve55zazv(("EVAL<br>*hpve55zazv*")) -- Any Triggers False --> gf3bwis6oi("Go To: Error<br>*gf3bwis6oi*")
    ru45xolut1(("EVAL<br>*ru45xolut1*")) --> 5d5o5ia81u("Is Validation Limit Reached?<br>*5d5o5ia81u*")
    rjau0njx5i("Form Button Check<br>*rjau0njx5i*") --> t92nqcnwux(("EVAL<br>*t92nqcnwux*"))
    rjau0njx5i("Form Button Check<br>*rjau0njx5i*") --> n5icn97kyh(("EVAL<br>*n5icn97kyh*"))
    8l8a54vefk(("EVAL<br>*8l8a54vefk*")) -- Any Triggers False --> ab91zkjrgx("Go To: Error<br>*ab91zkjrgx*")
    hpve55zazv(("EVAL<br>*hpve55zazv*")) --> 1vyzcyazgf("Validate verification code<br>*1vyzcyazgf*")
    sju60xf677(("EVAL<br>*sju60xf677*")) --> rjau0njx5i("Form Button Check<br>*rjau0njx5i*")
    8l8a54vefk(("EVAL<br>*8l8a54vefk*")) --> 527m4tr2s2("Verification Code Resent<br>*527m4tr2s2*")
    n5icn97kyh(("EVAL<br>*n5icn97kyh*")) --> 9lrqw38492("Resend Verification Code<br>*9lrqw38492*")
    xsb00g2t92("Set Validation Attempt To Zero<br>*xsb00g2t92*") --> qskpbqg2yf(("EVAL<br>*qskpbqg2yf*"))
    qskpbqg2yf(("EVAL<br>*qskpbqg2yf*")) --> s5yykzv8zd("Prompt For Verification Code<br>*s5yykzv8zd*")
    5d5o5ia81u("Is Validation Limit Reached?<br>*5d5o5ia81u*") --> hpve55zazv(("EVAL<br>*hpve55zazv*"))
    r8sc175hhf(("EVAL<br>*r8sc175hhf*")) -- Any Triggers False --> 8gqiq4sagn("Could not validate the verification code<br>*8gqiq4sagn*")
    t92nqcnwux(("EVAL<br>*t92nqcnwux*")) --> wfe8dz7k7v("Increment Validation Attempt<br>*wfe8dz7k7v*")
    1vyzcyazgf("Validate verification code<br>*1vyzcyazgf*") --> r8sc175hhf(("EVAL<br>*r8sc175hhf*"))
    wfe8dz7k7v("Increment Validation Attempt<br>*wfe8dz7k7v*") --> ru45xolut1(("EVAL<br>*ru45xolut1*"))
    9lrqw38492("Resend Verification Code<br>*9lrqw38492*") --> 8l8a54vefk(("EVAL<br>*8l8a54vefk*"))
    s5yykzv8zd("Prompt For Verification Code<br>*s5yykzv8zd*") --> sju60xf677(("EVAL<br>*sju60xf677*"))
    xbvfnq8o31("Error<br>*xbvfnq8o31*") --> 90g8cf6l2u(("EVAL<br>*90g8cf6l2u*"))
    90g8cf6l2u(("EVAL<br>*90g8cf6l2u*")) --> rfo66ayuok("Return Error Response<br>*rfo66ayuok*")

