flowchart LR
    fcajmc2304("Enable MFA<br>*fcajmc2304*") -- All True --> niwd9bvvyl(("EVAL<br>*niwd9bvvyl*"))
    niwd9bvvyl(("EVAL<br>*niwd9bvvyl*")) -- All True --> hmvyn1idpv("Enable MFA For User<br>*hmvyn1idpv*")
    f93pbyvrj2("Update Error Message<br>*f93pbyvrj2*") -- All True --> hqdb3y3i65(("EVAL<br>*hqdb3y3i65*"))
    4smjdpxvyk(("EVAL<br>*4smjdpxvyk*")) -- Any False --> sdvxpx62lw("Check If User Can Auto Enroll?<br>*sdvxpx62lw*")
    ltkdlim024(("EVAL<br>*ltkdlim024*")) -- All True --> bboqqsujae("Go To: Enable MFA<br>*bboqqsujae*")
    sdvxpx62lw("Check If User Can Auto Enroll?<br>*sdvxpx62lw*") -- All True --> zdzabypfcv(("EVAL<br>*zdzabypfcv*"))
    ltkdlim024(("EVAL<br>*ltkdlim024*")) -- Any False --> qzsm15mtm7("Go To: Error<br>*qzsm15mtm7*")
    2yjiwd8na2("Register Users Email As MFA Device<br>*2yjiwd8na2*") -- All True --> ltkdlim024(("EVAL<br>*ltkdlim024*"))
    7mu81oaiqx("Check If User Needs To Enter Email<br>*7mu81oaiqx*") -- All True --> 4smjdpxvyk(("EVAL<br>*4smjdpxvyk*"))
    4smjdpxvyk(("EVAL<br>*4smjdpxvyk*")) -- All True --> bvogh6r954("Email Form<br>*bvogh6r954*")
    rkuiz7q78p(("EVAL<br>*rkuiz7q78p*")) -- All True --> t9jyjrzivl("User action <br>*t9jyjrzivl*")
    2my7xaouma(("EVAL<br>*2my7xaouma*")) -- Any False --> z7l0uzlcxw("Go To: Error<br>*z7l0uzlcxw*")
    zdzabypfcv(("EVAL<br>*zdzabypfcv*")) -- All True --> 2yjiwd8na2("Register Users Email As MFA Device<br>*2yjiwd8na2*")
    zdzabypfcv(("EVAL<br>*zdzabypfcv*")) -- Any False --> 866hws1wwv("Go To: Create OTP Device<br>*866hws1wwv*")
    thtxgh5tye(("EVAL<br>*thtxgh5tye*")) -- Any False --> gnmbshsowi("Is Error Invalid Phone Number/Email Address?<br>*gnmbshsowi*")
    h7w9k7knl9(("EVAL<br>*h7w9k7knl9*")) -- Any False --> 2kjjqzwb93("Go To: Error<br>*2kjjqzwb93*")
    gnmbshsowi("Is Error Invalid Phone Number/Email Address?<br>*gnmbshsowi*") -- All True --> 2my7xaouma(("EVAL<br>*2my7xaouma*"))
    cxjw4q2ocj("Check Method Selected<br>*cxjw4q2ocj*") -- All True --> eczw2t8dc(("EVAL<br>*eczw2t8dc*"))
    wurft65sg6("Update Device ID<br>*wurft65sg6*") -- All True --> 3mzgwd5xbx(("EVAL<br>*3mzgwd5xbx*"))
    eczw2t8dc(("EVAL<br>*eczw2t8dc*")) -- All True --> eq7gbyti2l("Go To: Success<br>*eq7gbyti2l*")
    wms6o050jb("Check Status<br>*wms6o050jb*") -- All True --> s1axmvsfoq(("EVAL<br>*s1axmvsfoq*"))
    k90u9roz6q(("EVAL<br>*k90u9roz6q*")) -- All True --> 7mu81oaiqx("Check If User Needs To Enter Email<br>*7mu81oaiqx*")
    s1axmvsfoq(("EVAL<br>*s1axmvsfoq*")) -- All True --> wgvcj4rbmh("Go To: Error<br>*wgvcj4rbmh*")
    t9jyjrzivl("User action <br>*t9jyjrzivl*") -- All True --> qwx56pgrc8(("EVAL<br>*qwx56pgrc8*"))
    hqdb3y3i65(("EVAL<br>*hqdb3y3i65*")) -- Any False --> qz2aml0p13("Show Error From PingOne<br>*qz2aml0p13*")
    k44ne8uadp(("EVAL<br>*k44ne8uadp*")) -- All True --> cxjw4q2ocj("Check Method Selected<br>*cxjw4q2ocj*")
    wms6o050jb("Check Status<br>*wms6o050jb*") -- All True --> wpljz4km80(("EVAL<br>*wpljz4km80*"))
    cxjw4q2ocj("Check Method Selected<br>*cxjw4q2ocj*") -- All True --> ocsgnkoz0e(("EVAL<br>*ocsgnkoz0e*"))
    0s68cax470(("EVAL<br>*0s68cax470*")) -- All True --> uh95uv8tkc("User action <br>*uh95uv8tkc*")
    t9jyjrzivl("User action <br>*t9jyjrzivl*") -- All True --> jm2mglfpb1(("EVAL<br>*jm2mglfpb1*"))
    jm2mglfpb1(("EVAL<br>*jm2mglfpb1*")) -- All True --> gnhn62hei1("Go To: Authentication method selection<br>*gnhn62hei1*")
    wdmeq58d57(("EVAL<br>*wdmeq58d57*")) -- Any False --> 4he5hctlgw("Go To: Error<br>*4he5hctlgw*")
    wpljz4km80(("EVAL<br>*wpljz4km80*")) -- All True --> iru6qhsncf("Activate FIDO2 Device<br>*iru6qhsncf*")
    3mzgwd5xbx(("EVAL<br>*3mzgwd5xbx*")) -- All True --> rblpwgsav2("Display OTP Resent Message<br>*rblpwgsav2*")
    aduo0dhos1(("EVAL<br>*aduo0dhos1*")) -- All True --> te6t0zwohr("Read All Devices<br>*te6t0zwohr*")
    wms6o050jb("Check Status<br>*wms6o050jb*") -- All True --> 7z5i8o5gts(("EVAL<br>*7z5i8o5gts*"))
    p0xbtjpw30(("EVAL<br>*p0xbtjpw30*")) -- All True --> koamwnv0yf("Go To: Authentication method selection<br>*koamwnv0yf*")
    o3p0lu1ww2("Mask Phone Number/Email Address<br>*o3p0lu1ww2*") -- All True --> xceoebu0xh(("EVAL<br>*xceoebu0xh*"))
    rx5c39j4cx(("EVAL<br>*rx5c39j4cx*")) -- All True --> hili7n1bzj("Get Auth Method<br>*hili7n1bzj*")
    0ugqstlmcb(("EVAL<br>*0ugqstlmcb*")) -- All True --> vi56defl6q("Return Success Response<br>*vi56defl6q*")
    hili7n1bzj("Get Auth Method<br>*hili7n1bzj*") -- All True --> e9kw26s8me(("EVAL<br>*e9kw26s8me*"))
    qj9x404zi1(("EVAL<br>*qj9x404zi1*")) -- Any False --> bp8zqi2ee3("Go To: Error<br>*bp8zqi2ee3*")
    3zzt3vrb0k("Error Type<br>*3zzt3vrb0k*") -- All True --> ux1izu65m4(("EVAL<br>*ux1izu65m4*"))
    eh45uuo9ep("SMS/EMAIL OTP<br>*eh45uuo9ep*") -- All True --> 522ujtnujz(("EVAL<br>*522ujtnujz*"))
    qj9x404zi1(("EVAL<br>*qj9x404zi1*")) -- All True --> qz04gq3vc8("Go To: Success<br>*qz04gq3vc8*")
    v92cr3znpj("Enable MFA for user<br>*v92cr3znpj*") -- All True --> qj9x404zi1(("EVAL<br>*qj9x404zi1*"))
    h7w9k7knl9(("EVAL<br>*h7w9k7knl9*")) -- All True --> v92cr3znpj("Enable MFA for user<br>*v92cr3znpj*")
    iru6qhsncf("Activate FIDO2 Device<br>*iru6qhsncf*") -- All True --> h7w9k7knl9(("EVAL<br>*h7w9k7knl9*"))
    kbzya62ydz(("EVAL<br>*kbzya62ydz*")) -- All True --> wms6o050jb("Check Status<br>*wms6o050jb*")
    cxjw4q2ocj("Check Method Selected<br>*cxjw4q2ocj*") -- All True --> j0zgu89bdj(("EVAL<br>*j0zgu89bdj*"))
    j0zgu89bdj(("EVAL<br>*j0zgu89bdj*")) -- All True --> elvm9hs51q("Go To: FIDO2<br>*elvm9hs51q*")
    jozso5l9gu(("EVAL<br>*jozso5l9gu*")) -- All True --> wurft65sg6("Update Device ID<br>*wurft65sg6*")
    zqb2rroahz("Check User Selection <br>*zqb2rroahz*") -- All True --> eqr4ril6n5(("EVAL<br>*eqr4ril6n5*"))
    vc8o1wnpis("FIDO2<br>*vc8o1wnpis*") -- All True --> t0my8smuad(("EVAL<br>*t0my8smuad*"))
    wms6o050jb("Check Status<br>*wms6o050jb*") -- All True --> nxc2amxsdh(("EVAL<br>*nxc2amxsdh*"))
    ug7cydwdhw(("EVAL<br>*ug7cydwdhw*")) -- Any False --> 3zzt3vrb0k("Error Type<br>*3zzt3vrb0k*")
    ux1izu65m4(("EVAL<br>*ux1izu65m4*")) -- All True --> smnjhqmjr2("Go To: Error<br>*smnjhqmjr2*")
    zqb2rroahz("Check User Selection <br>*zqb2rroahz*") -- All True --> car7f7wytu(("EVAL<br>*car7f7wytu*"))
    zqb2rroahz("Check User Selection <br>*zqb2rroahz*") -- All True --> h00gom93pv(("EVAL<br>*h00gom93pv*"))
    t0my8smuad(("EVAL<br>*t0my8smuad*")) -- All True --> 5y2z6x314y("Create FIDO2 Device<br>*5y2z6x314y*")
    5y2z6x314y("Create FIDO2 Device<br>*5y2z6x314y*") -- All True --> 53fy0avvam(("EVAL<br>*53fy0avvam*"))
    jozso5l9gu(("EVAL<br>*jozso5l9gu*")) -- Any False --> i00dggjydf("Go To: Error<br>*i00dggjydf*")
    4cgf9zgns7("Get Origin<br>*4cgf9zgns7*") -- All True --> aduo0dhos1(("EVAL<br>*aduo0dhos1*"))
    53fy0avvam(("EVAL<br>*53fy0avvam*")) -- All True --> 6jkz2hx974("Pair FIDO2 Device<br>*6jkz2hx974*")
    car7f7wytu(("EVAL<br>*car7f7wytu*")) -- All True --> zva38sw55w("Go To: Authentication method selection<br>*zva38sw55w*")
    6jkz2hx974("Pair FIDO2 Device<br>*6jkz2hx974*") -- All True --> kbzya62ydz(("EVAL<br>*kbzya62ydz*"))
    ug7cydwdhw(("EVAL<br>*ug7cydwdhw*")) -- All True --> hmvyn1idpv("Enable MFA For User<br>*hmvyn1idpv*")
    8oqliw5zps("Set Device ID<br>*8oqliw5zps*") -- All True --> jacbwkhwfc(("EVAL<br>*jacbwkhwfc*"))
    wdmeq58d57(("EVAL<br>*wdmeq58d57*")) -- All True --> ybbdsq2fzf("Create device<br>*ybbdsq2fzf*")
    nxc2amxsdh(("EVAL<br>*nxc2amxsdh*")) -- All True --> 92ojigwmkh("Device Already Paired<br>*92ojigwmkh*")
    eqr4ril6n5(("EVAL<br>*eqr4ril6n5*")) -- All True --> kmq13sjqim("Go To: Activate OTP Device<br>*kmq13sjqim*")
    dc2mhwx86e("Create OTP Device<br>*dc2mhwx86e*") -- All True --> 9a49qb1y7k(("EVAL<br>*9a49qb1y7k*"))
    ih33zryjpu(("EVAL<br>*ih33zryjpu*")) -- All True --> uoppd09l5f("Activate OTP Device<br>*uoppd09l5f*")
    wtcsrlx6i1(("EVAL<br>*wtcsrlx6i1*")) -- All True --> zqb2rroahz("Check User Selection <br>*zqb2rroahz*")
    h00gom93pv(("EVAL<br>*h00gom93pv*")) -- All True --> slu740f2kg("Delete Previous Device<br>*slu740f2kg*")
    9a49qb1y7k(("EVAL<br>*9a49qb1y7k*")) -- All True --> pjzv5pikab("Create OTP Device<br>*pjzv5pikab*")
    vqogwo2qjm(("EVAL<br>*vqogwo2qjm*")) -- All True --> w4i8a0zmx4("Invalid OTP <br>*w4i8a0zmx4*")
    ybbdsq2fzf("Create device<br>*ybbdsq2fzf*") -- All True --> jozso5l9gu(("EVAL<br>*jozso5l9gu*"))
    uoppd09l5f("Activate OTP Device<br>*uoppd09l5f*") -- All True --> ug7cydwdhw(("EVAL<br>*ug7cydwdhw*"))
    3zzt3vrb0k("Error Type<br>*3zzt3vrb0k*") -- All True --> vqogwo2qjm(("EVAL<br>*vqogwo2qjm*"))
    8tr8nq23dr("Error<br>*8tr8nq23dr*") -- All True --> xa83bdvhbj(("EVAL<br>*xa83bdvhbj*"))
    hmvyn1idpv("Enable MFA For User<br>*hmvyn1idpv*") -- All True --> rx5c39j4cx(("EVAL<br>*rx5c39j4cx*"))
    uh95uv8tkc("User action <br>*uh95uv8tkc*") -- All True --> 3mjp355lsy(("EVAL<br>*3mjp355lsy*"))
    7qi7idcwvv("Activate OTP Device<br>*7qi7idcwvv*") -- All True --> ih33zryjpu(("EVAL<br>*ih33zryjpu*"))
    rx5c39j4cx(("EVAL<br>*rx5c39j4cx*")) -- Any False --> ehs2szm22u("Go To: Error<br>*ehs2szm22u*")
    xceoebu0xh(("EVAL<br>*xceoebu0xh*")) -- All True --> qdsmqnczwr("Prompt For OTP<br>*qdsmqnczwr*")
    jacbwkhwfc(("EVAL<br>*jacbwkhwfc*")) -- All True --> fc155lnlgf("Go To: SMS/EMAIL OTP<br>*fc155lnlgf*")
    thtxgh5tye(("EVAL<br>*thtxgh5tye*")) -- All True --> 8oqliw5zps("Set Device ID<br>*8oqliw5zps*")
    e9kw26s8me(("EVAL<br>*e9kw26s8me*")) -- All True --> ew8wmbtjs7("Go To: Success<br>*ew8wmbtjs7*")
    4m767nsx46("Success<br>*4m767nsx46*") -- All True --> 0ugqstlmcb(("EVAL<br>*0ugqstlmcb*"))
    ocsgnkoz0e(("EVAL<br>*ocsgnkoz0e*")) -- All True --> r0z9swupt6("Phone Number Form<br>*r0z9swupt6*")
    pjzv5pikab("Create OTP Device<br>*pjzv5pikab*") -- All True --> thtxgh5tye(("EVAL<br>*thtxgh5tye*"))
    3mjp355lsy(("EVAL<br>*3mjp355lsy*")) -- All True --> s0wuh3cmeu("Go To: Create OTP Device<br>*s0wuh3cmeu*")
    uyltkub1v7(("EVAL<br>*uyltkub1v7*")) -- All True --> igsfh12mz5("Go To: Authentication method selection<br>*igsfh12mz5*")
    522ujtnujz(("EVAL<br>*522ujtnujz*")) -- All True --> o3p0lu1ww2("Mask Phone Number/Email Address<br>*o3p0lu1ww2*")
    uh95uv8tkc("User action <br>*uh95uv8tkc*") -- All True --> uyltkub1v7(("EVAL<br>*uyltkub1v7*"))
    531xfigfe0(("EVAL<br>*531xfigfe0*")) -- All True --> qvja9ysrwp("Go To: Success<br>*qvja9ysrwp*")
    cxjw4q2ocj("Check Method Selected<br>*cxjw4q2ocj*") -- All True --> 531xfigfe0(("EVAL<br>*531xfigfe0*"))
    r0z9swupt6("Phone Number Form<br>*r0z9swupt6*") -- All True --> 0s68cax470(("EVAL<br>*0s68cax470*"))
    slu740f2kg("Delete Previous Device<br>*slu740f2kg*") -- All True --> wdmeq58d57(("EVAL<br>*wdmeq58d57*"))
    decvvhflks("Display Device Types<br>*decvvhflks*") -- All True --> k44ne8uadp(("EVAL<br>*k44ne8uadp*"))
    xa83bdvhbj(("EVAL<br>*xa83bdvhbj*")) -- All True --> 8tluota6xx("Return Error Response<br>*8tluota6xx*")
    qdsmqnczwr("Prompt For OTP<br>*qdsmqnczwr*") -- All True --> wtcsrlx6i1(("EVAL<br>*wtcsrlx6i1*"))
    orf96wndkv("Check If There Are Usable Device Types?<br>*orf96wndkv*") -- All True --> jh39me4hnk(("EVAL<br>*jh39me4hnk*"))
    53fy0avvam(("EVAL<br>*53fy0avvam*")) -- Any False --> zkdofvrmxu("Go To: Error<br>*zkdofvrmxu*")
    qj3vhzekmd(("EVAL<br>*qj3vhzekmd*")) -- All True --> fly72kbjyx("Go To: Authentication method selection<br>*fly72kbjyx*")
    jh39me4hnk(("EVAL<br>*jh39me4hnk*")) -- Any False --> cidzpskzeu("Go To: Error<br>*cidzpskzeu*")
    jh39me4hnk(("EVAL<br>*jh39me4hnk*")) -- All True --> 2tv7r1hqp9("Can User Register Another Device?<br>*2tv7r1hqp9*")
    qj3vhzekmd(("EVAL<br>*qj3vhzekmd*")) -- Any False --> bdbxj0ct3v("Go To: Error<br>*bdbxj0ct3v*")
    2tv7r1hqp9("Can User Register Another Device?<br>*2tv7r1hqp9*") -- All True --> qj3vhzekmd(("EVAL<br>*qj3vhzekmd*"))
    na4hef71sq("Gather Browser Information<br>*na4hef71sq*") -- All True --> tir7r8fvkp(("EVAL<br>*tir7r8fvkp*"))
    7z5i8o5gts(("EVAL<br>*7z5i8o5gts*")) -- All True --> 6de8yoq3eb("Wrong Relying Party ID<br>*6de8yoq3eb*")
    wms6o050jb("Check Status<br>*wms6o050jb*") -- All True --> p0xbtjpw30(("EVAL<br>*p0xbtjpw30*"))
    te6t0zwohr("Read All Devices<br>*te6t0zwohr*") -- All True --> p8n9w6rdgy(("EVAL<br>*p8n9w6rdgy*"))
    p8n9w6rdgy(("EVAL<br>*p8n9w6rdgy*")) -- All True --> na4hef71sq("Gather Browser Information<br>*na4hef71sq*")
    tir7r8fvkp(("EVAL<br>*tir7r8fvkp*")) -- All True --> kfqbhjjaqb("Filter Unusable Device Types<br>*kfqbhjjaqb*")
    2ewaah2axe(("EVAL<br>*2ewaah2axe*")) -- All True --> orf96wndkv("Check If There Are Usable Device Types?<br>*orf96wndkv*")
    2ewaah2axe(("EVAL<br>*2ewaah2axe*")) -- Any False --> 8h2rnuqdua("Go To: Error<br>*8h2rnuqdua*")
    kfqbhjjaqb("Filter Unusable Device Types<br>*kfqbhjjaqb*") -- All True --> 2ewaah2axe(("EVAL<br>*2ewaah2axe*"))
    qwx56pgrc8(("EVAL<br>*qwx56pgrc8*")) -- All True --> 7nzxn0tx9f("Go To: Create OTP Device<br>*7nzxn0tx9f*")
    bvogh6r954("Email Form<br>*bvogh6r954*") -- All True --> rkuiz7q78p(("EVAL<br>*rkuiz7q78p*"))
    p8n9w6rdgy(("EVAL<br>*p8n9w6rdgy*")) -- Any False --> 6kd2knl0eb("Go To: Error<br>*6kd2knl0eb*")
    cxjw4q2ocj("Check Method Selected<br>*cxjw4q2ocj*") -- All True --> k90u9roz6q(("EVAL<br>*k90u9roz6q*"))
    2my7xaouma(("EVAL<br>*2my7xaouma*")) -- All True --> f93pbyvrj2("Update Error Message<br>*f93pbyvrj2*")
    wc0jfkkr3z("Authentication method selection<br>*wc0jfkkr3z*") -- All True --> k9rrvndxtf(("EVAL<br>*k9rrvndxtf*"))
    k9rrvndxtf(("EVAL<br>*k9rrvndxtf*")) -- All True --> 2whff30xov("Mask Email Address<br>*2whff30xov*")
    2whff30xov("Mask Email Address<br>*2whff30xov*") -- All True --> h2d7rovpq5(("EVAL<br>*h2d7rovpq5*"))
    h2d7rovpq5(("EVAL<br>*h2d7rovpq5*")) -- All True --> decvvhflks("Display Device Types<br>*decvvhflks*")
    h2d7rovpq5(("EVAL<br>*h2d7rovpq5*")) -- Any False --> qwggt9vgg6("Go To: Error<br>*qwggt9vgg6*")
    xceoebu0xh(("EVAL<br>*xceoebu0xh*")) -- Any False --> 5rlurs22n4("Go To: Error<br>*5rlurs22n4*")

    linkStyle 0 stroke:#5F84BB,stroke-width:2px;
    linkStyle 1 stroke:#5F84BB,stroke-width:2px;
    linkStyle 2 stroke:#5F84BB,stroke-width:2px;
    linkStyle 3 stroke:#FCBC3E,stroke-width:2px;
    linkStyle 4 stroke:#5F84BB,stroke-width:2px;
    linkStyle 5 stroke:#5F84BB,stroke-width:2px;
    linkStyle 6 stroke:#FCBC3E,stroke-width:2px;
    linkStyle 7 stroke:#5F84BB,stroke-width:2px;
    linkStyle 8 stroke:#5F84BB,stroke-width:2px;
    linkStyle 9 stroke:#5F84BB,stroke-width:2px;
    linkStyle 10 stroke:#5F84BB,stroke-width:2px;
    linkStyle 11 stroke:#FCBC3E,stroke-width:2px;
    linkStyle 12 stroke:#5F84BB,stroke-width:2px;
    linkStyle 13 stroke:#FCBC3E,stroke-width:2px;
    linkStyle 14 stroke:#FCBC3E,stroke-width:2px;
    linkStyle 15 stroke:#FCBC3E,stroke-width:2px;
    linkStyle 16 stroke:#5F84BB,stroke-width:2px;
    linkStyle 17 stroke:#5F84BB,stroke-width:2px;
    linkStyle 18 stroke:#5F84BB,stroke-width:2px;
    linkStyle 19 stroke:#5F84BB,stroke-width:2px;
    linkStyle 20 stroke:#5F84BB,stroke-width:2px;
    linkStyle 21 stroke:#5F84BB,stroke-width:2px;
    linkStyle 22 stroke:#5F84BB,stroke-width:2px;
    linkStyle 23 stroke:#5F84BB,stroke-width:2px;
    linkStyle 24 stroke:#FCBC3E,stroke-width:2px;
    linkStyle 25 stroke:#5F84BB,stroke-width:2px;
    linkStyle 26 stroke:#5F84BB,stroke-width:2px;
    linkStyle 27 stroke:#5F84BB,stroke-width:2px;
    linkStyle 28 stroke:#5F84BB,stroke-width:2px;
    linkStyle 29 stroke:#5F84BB,stroke-width:2px;
    linkStyle 30 stroke:#5F84BB,stroke-width:2px;
    linkStyle 31 stroke:#FCBC3E,stroke-width:2px;
    linkStyle 32 stroke:#5F84BB,stroke-width:2px;
    linkStyle 33 stroke:#5F84BB,stroke-width:2px;
    linkStyle 34 stroke:#5F84BB,stroke-width:2px;
    linkStyle 35 stroke:#5F84BB,stroke-width:2px;
    linkStyle 36 stroke:#5F84BB,stroke-width:2px;
    linkStyle 37 stroke:#5F84BB,stroke-width:2px;
    linkStyle 38 stroke:#5F84BB,stroke-width:2px;
    linkStyle 39 stroke:#5F84BB,stroke-width:2px;
    linkStyle 40 stroke:#5F84BB,stroke-width:2px;
    linkStyle 41 stroke:#FCBC3E,stroke-width:2px;
    linkStyle 42 stroke:#5F84BB,stroke-width:2px;
    linkStyle 43 stroke:#5F84BB,stroke-width:2px;
    linkStyle 44 stroke:#5F84BB,stroke-width:2px;
    linkStyle 45 stroke:#5F84BB,stroke-width:2px;
    linkStyle 46 stroke:#5F84BB,stroke-width:2px;
    linkStyle 47 stroke:#5F84BB,stroke-width:2px;
    linkStyle 48 stroke:#5F84BB,stroke-width:2px;
    linkStyle 49 stroke:#5F84BB,stroke-width:2px;
    linkStyle 50 stroke:#5F84BB,stroke-width:2px;
    linkStyle 51 stroke:#5F84BB,stroke-width:2px;
    linkStyle 52 stroke:#5F84BB,stroke-width:2px;
    linkStyle 53 stroke:#5F84BB,stroke-width:2px;
    linkStyle 54 stroke:#5F84BB,stroke-width:2px;
    linkStyle 55 stroke:#FCBC3E,stroke-width:2px;
    linkStyle 56 stroke:#5F84BB,stroke-width:2px;
    linkStyle 57 stroke:#5F84BB,stroke-width:2px;
    linkStyle 58 stroke:#5F84BB,stroke-width:2px;
    linkStyle 59 stroke:#5F84BB,stroke-width:2px;
    linkStyle 60 stroke:#5F84BB,stroke-width:2px;
    linkStyle 61 stroke:#FCBC3E,stroke-width:2px;
    linkStyle 62 stroke:#5F84BB,stroke-width:2px;
    linkStyle 63 stroke:#5F84BB,stroke-width:2px;
    linkStyle 64 stroke:#5F84BB,stroke-width:2px;
    linkStyle 65 stroke:#5F84BB,stroke-width:2px;
    linkStyle 66 stroke:#5F84BB,stroke-width:2px;
    linkStyle 67 stroke:#5F84BB,stroke-width:2px;
    linkStyle 68 stroke:#5F84BB,stroke-width:2px;
    linkStyle 69 stroke:#5F84BB,stroke-width:2px;
    linkStyle 70 stroke:#5F84BB,stroke-width:2px;
    linkStyle 71 stroke:#5F84BB,stroke-width:2px;
    linkStyle 72 stroke:#5F84BB,stroke-width:2px;
    linkStyle 73 stroke:#5F84BB,stroke-width:2px;
    linkStyle 74 stroke:#5F84BB,stroke-width:2px;
    linkStyle 75 stroke:#5F84BB,stroke-width:2px;
    linkStyle 76 stroke:#5F84BB,stroke-width:2px;
    linkStyle 77 stroke:#5F84BB,stroke-width:2px;
    linkStyle 78 stroke:#5F84BB,stroke-width:2px;
    linkStyle 79 stroke:#5F84BB,stroke-width:2px;
    linkStyle 80 stroke:#5F84BB,stroke-width:2px;
    linkStyle 81 stroke:#5F84BB,stroke-width:2px;
    linkStyle 82 stroke:#5F84BB,stroke-width:2px;
    linkStyle 83 stroke:#5F84BB,stroke-width:2px;
    linkStyle 84 stroke:#FCBC3E,stroke-width:2px;
    linkStyle 85 stroke:#5F84BB,stroke-width:2px;
    linkStyle 86 stroke:#5F84BB,stroke-width:2px;
    linkStyle 87 stroke:#5F84BB,stroke-width:2px;
    linkStyle 88 stroke:#5F84BB,stroke-width:2px;
    linkStyle 89 stroke:#5F84BB,stroke-width:2px;
    linkStyle 90 stroke:#5F84BB,stroke-width:2px;
    linkStyle 91 stroke:#5F84BB,stroke-width:2px;
    linkStyle 92 stroke:#5F84BB,stroke-width:2px;
    linkStyle 93 stroke:#5F84BB,stroke-width:2px;
    linkStyle 94 stroke:#5F84BB,stroke-width:2px;
    linkStyle 95 stroke:#5F84BB,stroke-width:2px;
    linkStyle 96 stroke:#5F84BB,stroke-width:2px;
    linkStyle 97 stroke:#5F84BB,stroke-width:2px;
    linkStyle 98 stroke:#5F84BB,stroke-width:2px;
    linkStyle 99 stroke:#5F84BB,stroke-width:2px;
    linkStyle 100 stroke:#5F84BB,stroke-width:2px;
    linkStyle 101 stroke:#5F84BB,stroke-width:2px;
    linkStyle 102 stroke:#5F84BB,stroke-width:2px;
    linkStyle 103 stroke:#5F84BB,stroke-width:2px;
    linkStyle 104 stroke:#FCBC3E,stroke-width:2px;
    linkStyle 105 stroke:#5F84BB,stroke-width:2px;
    linkStyle 106 stroke:#FCBC3E,stroke-width:2px;
    linkStyle 107 stroke:#5F84BB,stroke-width:2px;
    linkStyle 108 stroke:#FCBC3E,stroke-width:2px;
    linkStyle 109 stroke:#5F84BB,stroke-width:2px;
    linkStyle 110 stroke:#5F84BB,stroke-width:2px;
    linkStyle 111 stroke:#5F84BB,stroke-width:2px;
    linkStyle 112 stroke:#5F84BB,stroke-width:2px;
    linkStyle 113 stroke:#5F84BB,stroke-width:2px;
    linkStyle 114 stroke:#5F84BB,stroke-width:2px;
    linkStyle 115 stroke:#5F84BB,stroke-width:2px;
    linkStyle 116 stroke:#5F84BB,stroke-width:2px;
    linkStyle 117 stroke:#FCBC3E,stroke-width:2px;
    linkStyle 118 stroke:#5F84BB,stroke-width:2px;
    linkStyle 119 stroke:#5F84BB,stroke-width:2px;
    linkStyle 120 stroke:#5F84BB,stroke-width:2px;
    linkStyle 121 stroke:#FCBC3E,stroke-width:2px;
    linkStyle 122 stroke:#5F84BB,stroke-width:2px;
    linkStyle 123 stroke:#5F84BB,stroke-width:2px;
    linkStyle 124 stroke:#5F84BB,stroke-width:2px;
    linkStyle 125 stroke:#5F84BB,stroke-width:2px;
    linkStyle 126 stroke:#5F84BB,stroke-width:2px;
    linkStyle 127 stroke:#5F84BB,stroke-width:2px;
    linkStyle 128 stroke:#FCBC3E,stroke-width:2px;
    linkStyle 129 stroke:#FCBC3E,stroke-width:2px;
