flowchart LR
    nc1ozqg2dy("Disable User<br>*nc1ozqg2dy*") --> ymg2y1p8tf(("EVAL<br>*ymg2y1p8tf*"))
    7050iwhzic("Check if Risk ID is empty<br>*7050iwhzic*") --> p46u12kavc(("EVAL<br>*p46u12kavc*"))
    m1lp5172g7("PingOne Protect Analysis<br>*m1lp5172g7*") --> zpg6zu1p21(("EVAL<br>*zpg6zu1p21*"))
    mxiurb5xux("Send email for threat detected<br>*mxiurb5xux*") --> jozexysssa(("EVAL<br>*jozexysssa*"))
    zmdygh0diw("Check if RiskID is empty<br>*zmdygh0diw*") --> x1gd8ktif6(("EVAL<br>*x1gd8ktif6*"))
    jozexysssa(("EVAL<br>*jozexysssa*")) --> nc1ozqg2dy("Disable User<br>*nc1ozqg2dy*")
    8fh7taswpw(("EVAL<br>*8fh7taswpw*")) --> g3ie4cp1z5("Find user details<br>*g3ie4cp1z5*")
    g3ie4cp1z5("Find user details<br>*g3ie4cp1z5*") --> 0gubix0onw(("EVAL<br>*0gubix0onw*"))
    82g5jqcpg1(("EVAL<br>*82g5jqcpg1*")) -- Any Triggers False --> 5pgnxcibnw("PingOne Notifications<br>*5pgnxcibnw*")
    lonpqbsfiu(("EVAL<br>*lonpqbsfiu*")) -- Any Triggers False --> yj3z2ix7ge("Find user details<br>*yj3z2ix7ge*")
    p46u12kavc(("EVAL<br>*p46u12kavc*")) -- All Triggers False --> 7dwvsl8sa8("Update Risk Evaluation - FAILURE<br>*7dwvsl8sa8*")
    u0kjt3cxvi(("EVAL<br>*u0kjt3cxvi*")) --> 7050iwhzic("Check if Risk ID is empty<br>*7050iwhzic*")
    c69lo2tfh8(("EVAL<br>*c69lo2tfh8*")) --> xj97e6huu4("Check for KNOWN DEVICE<br>*xj97e6huu4*")
    yj3z2ix7ge("Find user details<br>*yj3z2ix7ge*") --> 82g5jqcpg1(("EVAL<br>*82g5jqcpg1*"))
    8u4731kx7c(("EVAL<br>*8u4731kx7c*")) --> o4xxassgqz("Risk Score from PingOne Protect<br>*o4xxassgqz*")
    5pgnxcibnw("PingOne Notifications<br>*5pgnxcibnw*") --> 8u4731kx7c(("EVAL<br>*8u4731kx7c*"))
    3pbs4ekm6u("Is Validation Limit Reached?<br>*3pbs4ekm6u*") --> 1brhauigps(("EVAL<br>*1brhauigps*"))
    c6tyb3dxi1(("EVAL<br>*c6tyb3dxi1*")) -- Any Triggers False --> ccqivhr3uh("Set error message<br>*ccqivhr3uh*")
    n0ympwqzwl(("EVAL<br>*n0ympwqzwl*")) --> z1uxnr4psu("Set Validation Attempt To Zero<br>*z1uxnr4psu*")
    h4u1as8yg4("Recovery Code Form<br>*h4u1as8yg4*") --> n9tgrbpiz4(("EVAL<br>*n9tgrbpiz4*"))
    ccqivhr3uh("Set error message<br>*ccqivhr3uh*") --> uh6ap9pj4p(("EVAL<br>*uh6ap9pj4p*"))
    zvl6xidgq9(("EVAL<br>*zvl6xidgq9*")) -- All Triggers False --> h4u1as8yg4("Recovery Code Form<br>*h4u1as8yg4*")
    z1uxnr4psu("Set Validation Attempt To Zero<br>*z1uxnr4psu*") --> zvl6xidgq9(("EVAL<br>*zvl6xidgq9*"))
    uh6ap9pj4p(("EVAL<br>*uh6ap9pj4p*")) --> 5vhs0j1lcd("Update error message<br>*5vhs0j1lcd*")
    1brhauigps(("EVAL<br>*1brhauigps*")) -- Any Triggers False --> xebw2nujq5("Go To: Error<br>*xebw2nujq5*")
    t6hyz30ejn(("EVAL<br>*t6hyz30ejn*")) --> rfwgqmb87x("Resend recovery code<br>*rfwgqmb87x*")
    mcc4xn7khm(("EVAL<br>*mcc4xn7khm*")) --> ux2xzdhk0a("Does User Have Existing Password<br>*ux2xzdhk0a*")
    1brhauigps(("EVAL<br>*1brhauigps*")) --> p7gnqv4r4t("Set New Password<br>*p7gnqv4r4t*")
    n0ympwqzwl(("EVAL<br>*n0ympwqzwl*")) -- Any Triggers False --> ycc8uizvh4("Go To: Error<br>*ycc8uizvh4*")
    9o0jtjpq4i(("EVAL<br>*9o0jtjpq4i*")) -- Any Triggers False --> gm535zgls3("Passwords Do Not Match Error<br>*gm535zgls3*")
    4mpcqubv22(("EVAL<br>*4mpcqubv22*")) --> tfdqp94azq("OTP Resent Message<br>*tfdqp94azq*")
    bl9wn96q7z(("EVAL<br>*bl9wn96q7z*")) --> ao6h6cnxrq("Go To: Forgot Password Form<br>*ao6h6cnxrq*")
    rtv1hwltfy("Split By Users Selection<br>*rtv1hwltfy*") --> bl9wn96q7z(("EVAL<br>*bl9wn96q7z*"))
    mkork4kg94(("EVAL<br>*mkork4kg94*")) --> km7ojt5kyt("Return Success Response<br>*km7ojt5kyt*")
    c6tyb3dxi1(("EVAL<br>*c6tyb3dxi1*")) --> jb2xut5506("Display Success Message<br>*jb2xut5506*")
    mcc4xn7khm(("EVAL<br>*mcc4xn7khm*")) -- Any Triggers False --> ixpij6bdtq("No User Found Error<br>*ixpij6bdtq*")
    jb2xut5506("Display Success Message<br>*jb2xut5506*") --> wy1q3vva1r(("EVAL<br>*wy1q3vva1r*"))
    klrsk927mu("Forgot Password Form<br>*klrsk927mu*") --> c52w1izn8f(("EVAL<br>*c52w1izn8f*"))
    fecpsdg3u3(("EVAL<br>*fecpsdg3u3*")) --> 16hlhgpr5h("Verify Passwords Match<br>*16hlhgpr5h*")
    eph6l2tfnr(("EVAL<br>*eph6l2tfnr*")) -- Any Triggers False --> fzf96tttyw("Go To: Error<br>*fzf96tttyw*")
    u0kjt3cxvi(("EVAL<br>*u0kjt3cxvi*")) --> br93gz6bmz("Return Error Response<br>*br93gz6bmz*")
    xd56mfv9sc("NOP UI Page<br>*xd56mfv9sc*") --> n9k3edxufj(("EVAL<br>*n9k3edxufj*"))
    n9k3edxufj(("EVAL<br>*n9k3edxufj*")) --> klrsk927mu("Forgot Password Form<br>*klrsk927mu*")
    b9635u4i3w(("EVAL<br>*b9635u4i3w*")) --> klrsk927mu("Forgot Password Form<br>*klrsk927mu*")
    rtv1hwltfy("Split By Users Selection<br>*rtv1hwltfy*") --> fecpsdg3u3(("EVAL<br>*fecpsdg3u3*"))
    k0gh9sf1l8(("EVAL<br>*k0gh9sf1l8*")) -- All Triggers False --> 0jvt7xvej2("Lookup User<br>*0jvt7xvej2*")
    ux2xzdhk0a("Does User Have Existing Password<br>*ux2xzdhk0a*") --> eph6l2tfnr(("EVAL<br>*eph6l2tfnr*"))
    dvr3wi8hib("Split By Users Selection<br>*dvr3wi8hib*") --> e6u7p021mj(("EVAL<br>*e6u7p021mj*"))
    dvr3wi8hib("Split By Users Selection<br>*dvr3wi8hib*") --> v28wjjz61p(("EVAL<br>*v28wjjz61p*"))
    eph6l2tfnr(("EVAL<br>*eph6l2tfnr*")) -- Value Not Found --> ujwd58v2j5("Send Recovery Code<br>*ujwd58v2j5*")
    o88xkrpbve("Forgot Password Form<br>*o88xkrpbve*") --> b9635u4i3w(("EVAL<br>*b9635u4i3w*"))
    ujwd58v2j5("Send Recovery Code<br>*ujwd58v2j5*") --> n0ympwqzwl(("EVAL<br>*n0ympwqzwl*"))
    rfwgqmb87x("Resend recovery code<br>*rfwgqmb87x*") --> 4mpcqubv22(("EVAL<br>*4mpcqubv22*"))
    c52w1izn8f(("EVAL<br>*c52w1izn8f*")) --> dvr3wi8hib("Split By Users Selection<br>*dvr3wi8hib*")
    0jvt7xvej2("Lookup User<br>*0jvt7xvej2*") --> mcc4xn7khm(("EVAL<br>*mcc4xn7khm*"))
    o8lq26j99n("Error<br>*o8lq26j99n*") --> u0kjt3cxvi(("EVAL<br>*u0kjt3cxvi*"))
    j3hvs9dks4("Success<br>*j3hvs9dks4*") --> mkork4kg94(("EVAL<br>*mkork4kg94*"))
    e6u7p021mj(("EVAL<br>*e6u7p021mj*")) --> hu2l38mo64("Go To: Success<br>*hu2l38mo64*")
    rtv1hwltfy("Split By Users Selection<br>*rtv1hwltfy*") --> t6hyz30ejn(("EVAL<br>*t6hyz30ejn*"))
    4mpcqubv22(("EVAL<br>*4mpcqubv22*")) -- Any Triggers False --> vp9pfw2l9i("Go To: Error<br>*vp9pfw2l9i*")
    wy1q3vva1r(("EVAL<br>*wy1q3vva1r*")) --> sili5r3wur("Go To: Success<br>*sili5r3wur*")
    n9tgrbpiz4(("EVAL<br>*n9tgrbpiz4*")) --> rtv1hwltfy("Split By Users Selection<br>*rtv1hwltfy*")
    p7gnqv4r4t("Set New Password<br>*p7gnqv4r4t*") --> c6tyb3dxi1(("EVAL<br>*c6tyb3dxi1*"))
    16hlhgpr5h("Verify Passwords Match<br>*16hlhgpr5h*") --> 9o0jtjpq4i(("EVAL<br>*9o0jtjpq4i*"))
    kj7e51zikv(("EVAL<br>*kj7e51zikv*")) --> jx18l5yjj0("Invalid password<br>*jx18l5yjj0*")
    xkvo347q5m(("EVAL<br>*xkvo347q5m*")) --> 3pbs4ekm6u("Is Validation Limit Reached?<br>*3pbs4ekm6u*")
    v4rlsooi5t("Increment Validation Attempt<br>*v4rlsooi5t*") --> xkvo347q5m(("EVAL<br>*xkvo347q5m*"))
    9o0jtjpq4i(("EVAL<br>*9o0jtjpq4i*")) --> v4rlsooi5t("Increment Validation Attempt<br>*v4rlsooi5t*")
    5vhs0j1lcd("Update error message<br>*5vhs0j1lcd*") --> kj7e51zikv(("EVAL<br>*kj7e51zikv*"))
    xj97e6huu4("Check for KNOWN DEVICE<br>*xj97e6huu4*") --> lonpqbsfiu(("EVAL<br>*lonpqbsfiu*"))
    zpg6zu1p21(("EVAL<br>*zpg6zu1p21*")) --> m71wjatj9v("Invoke PingOne Protect subflow<br>*m71wjatj9v*")
    m71wjatj9v("Invoke PingOne Protect subflow<br>*m71wjatj9v*") --> pz7469or4k(("EVAL<br>*pz7469or4k*"))
    pz7469or4k(("EVAL<br>*pz7469or4k*")) --> 5mvyk1j6oz("Get Values from PingOne Protect analysis<br>*5mvyk1j6oz*")
    pz7469or4k(("EVAL<br>*pz7469or4k*")) -- Any Triggers False --> akl8h5d22x("Get Values from PingOne Protect analysis<br>*akl8h5d22x*")
    5mvyk1j6oz("Get Values from PingOne Protect analysis<br>*5mvyk1j6oz*") --> c69lo2tfh8(("EVAL<br>*c69lo2tfh8*"))
    lonpqbsfiu(("EVAL<br>*lonpqbsfiu*")) --> o4xxassgqz("Risk Score from PingOne Protect<br>*o4xxassgqz*")
    o4xxassgqz("Risk Score from PingOne Protect<br>*o4xxassgqz*") --> f4he7cr9jf(("EVAL<br>*f4he7cr9jf*"))
    f4he7cr9jf(("EVAL<br>*f4he7cr9jf*")) --> llvrblwi3q("Return to calling node<br>*llvrblwi3q*")
    o4xxassgqz("Risk Score from PingOne Protect<br>*o4xxassgqz*") --> tr6ask2nn2(("EVAL<br>*tr6ask2nn2*"))
    tr6ask2nn2(("EVAL<br>*tr6ask2nn2*")) --> 3b5q91z8tx("Return to calling node<br>*3b5q91z8tx*")
    o4xxassgqz("Risk Score from PingOne Protect<br>*o4xxassgqz*") --> 4tfnhsx2bw(("EVAL<br>*4tfnhsx2bw*"))
    mkork4kg94(("EVAL<br>*mkork4kg94*")) --> zmdygh0diw("Check if RiskID is empty<br>*zmdygh0diw*")
    akl8h5d22x("Get Values from PingOne Protect analysis<br>*akl8h5d22x*") --> 8fh7taswpw(("EVAL<br>*8fh7taswpw*"))
    v28wjjz61p(("EVAL<br>*v28wjjz61p*")) --> 0wx52cpso1("Go To: PingOne Protect Analysis<br>*0wx52cpso1*")
    0gubix0onw(("EVAL<br>*0gubix0onw*")) --> mxiurb5xux("Send email for threat detected<br>*mxiurb5xux*")
    ymg2y1p8tf(("EVAL<br>*ymg2y1p8tf*")) --> 8eguhqxqpn("Go To: Error<br>*8eguhqxqpn*")
    0wx52cpso1("Go To: PingOne Protect Analysis<br>*0wx52cpso1*") --> k0gh9sf1l8(("EVAL<br>*k0gh9sf1l8*"))
    4tfnhsx2bw(("EVAL<br>*4tfnhsx2bw*")) --> rsu5s043qp("Go To: Error<br>*rsu5s043qp*")
    x1gd8ktif6(("EVAL<br>*x1gd8ktif6*")) -- All Triggers False --> hhileu4ydz("Update Risk Evaluation - SUCCESS<br>*hhileu4ydz*")

