flowchart LR
    nc1ozqg2dy("Disable User<br>*nc1ozqg2dy*") -- All True --> ymg2y1p8tf(("EVAL<br>*ymg2y1p8tf*"))
    7050iwhzic("Check if Risk ID is empty<br>*7050iwhzic*") -- All True --> p46u12kavc(("EVAL<br>*p46u12kavc*"))
    m1lp5172g7("PingOne Protect Analysis<br>*m1lp5172g7*") -- All True --> zpg6zu1p21(("EVAL<br>*zpg6zu1p21*"))
    mxiurb5xux("Send email for threat detected<br>*mxiurb5xux*") -- All True --> jozexysssa(("EVAL<br>*jozexysssa*"))
    zmdygh0diw("Check if RiskID is empty<br>*zmdygh0diw*") -- All True --> x1gd8ktif6(("EVAL<br>*x1gd8ktif6*"))
    jozexysssa(("EVAL<br>*jozexysssa*")) -- All True --> nc1ozqg2dy("Disable User<br>*nc1ozqg2dy*")
    8fh7taswpw(("EVAL<br>*8fh7taswpw*")) -- All True --> g3ie4cp1z5("Find user details<br>*g3ie4cp1z5*")
    g3ie4cp1z5("Find user details<br>*g3ie4cp1z5*") -- All True --> 0gubix0onw(("EVAL<br>*0gubix0onw*"))
    82g5jqcpg1(("EVAL<br>*82g5jqcpg1*")) -- Any False --> 5pgnxcibnw("PingOne Notifications<br>*5pgnxcibnw*")
    lonpqbsfiu(("EVAL<br>*lonpqbsfiu*")) -- Any False --> yj3z2ix7ge("Find user details<br>*yj3z2ix7ge*")
    p46u12kavc(("EVAL<br>*p46u12kavc*")) -- All False --> 7dwvsl8sa8("Update Risk Evaluation - FAILURE<br>*7dwvsl8sa8*")
    u0kjt3cxvi(("EVAL<br>*u0kjt3cxvi*")) -- All True --> 7050iwhzic("Check if Risk ID is empty<br>*7050iwhzic*")
    c69lo2tfh8(("EVAL<br>*c69lo2tfh8*")) -- All True --> xj97e6huu4("Check for KNOWN DEVICE<br>*xj97e6huu4*")
    yj3z2ix7ge("Find user details<br>*yj3z2ix7ge*") -- All True --> 82g5jqcpg1(("EVAL<br>*82g5jqcpg1*"))
    8u4731kx7c(("EVAL<br>*8u4731kx7c*")) -- All True --> o4xxassgqz("Risk Score from PingOne Protect<br>*o4xxassgqz*")
    5pgnxcibnw("PingOne Notifications<br>*5pgnxcibnw*") -- All True --> 8u4731kx7c(("EVAL<br>*8u4731kx7c*"))
    3pbs4ekm6u("Is Validation Limit Reached?<br>*3pbs4ekm6u*") -- All True --> 1brhauigps(("EVAL<br>*1brhauigps*"))
    c6tyb3dxi1(("EVAL<br>*c6tyb3dxi1*")) -- Any False --> ccqivhr3uh("Set error message<br>*ccqivhr3uh*")
    n0ympwqzwl(("EVAL<br>*n0ympwqzwl*")) -- All True --> z1uxnr4psu("Set Validation Attempt To Zero<br>*z1uxnr4psu*")
    h4u1as8yg4("Recovery Code Form<br>*h4u1as8yg4*") -- All True --> n9tgrbpiz4(("EVAL<br>*n9tgrbpiz4*"))
    ccqivhr3uh("Set error message<br>*ccqivhr3uh*") -- All True --> uh6ap9pj4p(("EVAL<br>*uh6ap9pj4p*"))
    zvl6xidgq9(("EVAL<br>*zvl6xidgq9*")) -- All True --> h4u1as8yg4("Recovery Code Form<br>*h4u1as8yg4*")
    z1uxnr4psu("Set Validation Attempt To Zero<br>*z1uxnr4psu*") -- All True --> zvl6xidgq9(("EVAL<br>*zvl6xidgq9*"))
    uh6ap9pj4p(("EVAL<br>*uh6ap9pj4p*")) -- All True --> 5vhs0j1lcd("Update error message<br>*5vhs0j1lcd*")
    1brhauigps(("EVAL<br>*1brhauigps*")) -- Any False --> xebw2nujq5("Go To: Error<br>*xebw2nujq5*")
    t6hyz30ejn(("EVAL<br>*t6hyz30ejn*")) -- All True --> rfwgqmb87x("Resend recovery code<br>*rfwgqmb87x*")
    mcc4xn7khm(("EVAL<br>*mcc4xn7khm*")) -- All True --> ux2xzdhk0a("Does User Have Existing Password<br>*ux2xzdhk0a*")
    1brhauigps(("EVAL<br>*1brhauigps*")) -- All True --> p7gnqv4r4t("Set New Password<br>*p7gnqv4r4t*")
    n0ympwqzwl(("EVAL<br>*n0ympwqzwl*")) -- Any False --> ycc8uizvh4("Go To: Error<br>*ycc8uizvh4*")
    9o0jtjpq4i(("EVAL<br>*9o0jtjpq4i*")) -- Any False --> gm535zgls3("Passwords Do Not Match Error<br>*gm535zgls3*")
    4mpcqubv22(("EVAL<br>*4mpcqubv22*")) -- All True --> tfdqp94azq("OTP Resent Message<br>*tfdqp94azq*")
    bl9wn96q7z(("EVAL<br>*bl9wn96q7z*")) -- All True --> ao6h6cnxrq("Go To: Forgot Password Form<br>*ao6h6cnxrq*")
    rtv1hwltfy("Split By Users Selection<br>*rtv1hwltfy*") -- All True --> bl9wn96q7z(("EVAL<br>*bl9wn96q7z*"))
    mkork4kg94(("EVAL<br>*mkork4kg94*")) -- All True --> km7ojt5kyt("Return Success Response<br>*km7ojt5kyt*")
    c6tyb3dxi1(("EVAL<br>*c6tyb3dxi1*")) -- All True --> jb2xut5506("Display Success Message<br>*jb2xut5506*")
    mcc4xn7khm(("EVAL<br>*mcc4xn7khm*")) -- Any False --> ixpij6bdtq("No User Found Error<br>*ixpij6bdtq*")
    jb2xut5506("Display Success Message<br>*jb2xut5506*") -- All True --> wy1q3vva1r(("EVAL<br>*wy1q3vva1r*"))
    klrsk927mu("Forgot Password Form<br>*klrsk927mu*") -- All True --> c52w1izn8f(("EVAL<br>*c52w1izn8f*"))
    fecpsdg3u3(("EVAL<br>*fecpsdg3u3*")) -- All True --> 16hlhgpr5h("Verify Passwords Match<br>*16hlhgpr5h*")
    eph6l2tfnr(("EVAL<br>*eph6l2tfnr*")) -- Any False --> fzf96tttyw("Go To: Error<br>*fzf96tttyw*")
    u0kjt3cxvi(("EVAL<br>*u0kjt3cxvi*")) -- All True --> br93gz6bmz("Return Error Response<br>*br93gz6bmz*")
    xd56mfv9sc("NOP UI Page<br>*xd56mfv9sc*") -- All True --> n9k3edxufj(("EVAL<br>*n9k3edxufj*"))
    n9k3edxufj(("EVAL<br>*n9k3edxufj*")) -- All True --> klrsk927mu("Forgot Password Form<br>*klrsk927mu*")
    b9635u4i3w(("EVAL<br>*b9635u4i3w*")) -- All True --> klrsk927mu("Forgot Password Form<br>*klrsk927mu*")
    rtv1hwltfy("Split By Users Selection<br>*rtv1hwltfy*") -- All True --> fecpsdg3u3(("EVAL<br>*fecpsdg3u3*"))
    k0gh9sf1l8(("EVAL<br>*k0gh9sf1l8*")) -- All True --> 0jvt7xvej2("Lookup User<br>*0jvt7xvej2*")
    ux2xzdhk0a("Does User Have Existing Password<br>*ux2xzdhk0a*") -- All True --> eph6l2tfnr(("EVAL<br>*eph6l2tfnr*"))
    dvr3wi8hib("Split By Users Selection<br>*dvr3wi8hib*") -- All True --> e6u7p021mj(("EVAL<br>*e6u7p021mj*"))
    dvr3wi8hib("Split By Users Selection<br>*dvr3wi8hib*") -- All True --> v28wjjz61p(("EVAL<br>*v28wjjz61p*"))
    eph6l2tfnr(("EVAL<br>*eph6l2tfnr*")) -- All True --> ujwd58v2j5("Send Recovery Code<br>*ujwd58v2j5*")
    o88xkrpbve("Forgot Password Form<br>*o88xkrpbve*") -- All True --> b9635u4i3w(("EVAL<br>*b9635u4i3w*"))
    ujwd58v2j5("Send Recovery Code<br>*ujwd58v2j5*") -- All True --> n0ympwqzwl(("EVAL<br>*n0ympwqzwl*"))
    rfwgqmb87x("Resend recovery code<br>*rfwgqmb87x*") -- All True --> 4mpcqubv22(("EVAL<br>*4mpcqubv22*"))
    c52w1izn8f(("EVAL<br>*c52w1izn8f*")) -- All True --> dvr3wi8hib("Split By Users Selection<br>*dvr3wi8hib*")
    0jvt7xvej2("Lookup User<br>*0jvt7xvej2*") -- All True --> mcc4xn7khm(("EVAL<br>*mcc4xn7khm*"))
    o8lq26j99n("Error<br>*o8lq26j99n*") -- All True --> u0kjt3cxvi(("EVAL<br>*u0kjt3cxvi*"))
    j3hvs9dks4("Success<br>*j3hvs9dks4*") -- All True --> mkork4kg94(("EVAL<br>*mkork4kg94*"))
    e6u7p021mj(("EVAL<br>*e6u7p021mj*")) -- All True --> hu2l38mo64("Go To: Success<br>*hu2l38mo64*")
    rtv1hwltfy("Split By Users Selection<br>*rtv1hwltfy*") -- All True --> t6hyz30ejn(("EVAL<br>*t6hyz30ejn*"))
    4mpcqubv22(("EVAL<br>*4mpcqubv22*")) -- Any False --> vp9pfw2l9i("Go To: Error<br>*vp9pfw2l9i*")
    wy1q3vva1r(("EVAL<br>*wy1q3vva1r*")) -- All True --> sili5r3wur("Go To: Success<br>*sili5r3wur*")
    n9tgrbpiz4(("EVAL<br>*n9tgrbpiz4*")) -- All True --> rtv1hwltfy("Split By Users Selection<br>*rtv1hwltfy*")
    p7gnqv4r4t("Set New Password<br>*p7gnqv4r4t*") -- All True --> c6tyb3dxi1(("EVAL<br>*c6tyb3dxi1*"))
    16hlhgpr5h("Verify Passwords Match<br>*16hlhgpr5h*") -- All True --> 9o0jtjpq4i(("EVAL<br>*9o0jtjpq4i*"))
    kj7e51zikv(("EVAL<br>*kj7e51zikv*")) -- All True --> jx18l5yjj0("Invalid password<br>*jx18l5yjj0*")
    xkvo347q5m(("EVAL<br>*xkvo347q5m*")) -- All True --> 3pbs4ekm6u("Is Validation Limit Reached?<br>*3pbs4ekm6u*")
    v4rlsooi5t("Increment Validation Attempt<br>*v4rlsooi5t*") -- All True --> xkvo347q5m(("EVAL<br>*xkvo347q5m*"))
    9o0jtjpq4i(("EVAL<br>*9o0jtjpq4i*")) -- All True --> v4rlsooi5t("Increment Validation Attempt<br>*v4rlsooi5t*")
    5vhs0j1lcd("Update error message<br>*5vhs0j1lcd*") -- All True --> kj7e51zikv(("EVAL<br>*kj7e51zikv*"))
    xj97e6huu4("Check for KNOWN DEVICE<br>*xj97e6huu4*") -- All True --> lonpqbsfiu(("EVAL<br>*lonpqbsfiu*"))
    zpg6zu1p21(("EVAL<br>*zpg6zu1p21*")) -- All True --> m71wjatj9v("Invoke PingOne Protect subflow<br>*m71wjatj9v*")
    m71wjatj9v("Invoke PingOne Protect subflow<br>*m71wjatj9v*") -- All True --> pz7469or4k(("EVAL<br>*pz7469or4k*"))
    pz7469or4k(("EVAL<br>*pz7469or4k*")) -- All True --> 5mvyk1j6oz("Get Values from PingOne Protect analysis<br>*5mvyk1j6oz*")
    pz7469or4k(("EVAL<br>*pz7469or4k*")) -- Any False --> akl8h5d22x("Get Values from PingOne Protect analysis<br>*akl8h5d22x*")
    5mvyk1j6oz("Get Values from PingOne Protect analysis<br>*5mvyk1j6oz*") -- All True --> c69lo2tfh8(("EVAL<br>*c69lo2tfh8*"))
    lonpqbsfiu(("EVAL<br>*lonpqbsfiu*")) -- All True --> o4xxassgqz("Risk Score from PingOne Protect<br>*o4xxassgqz*")
    o4xxassgqz("Risk Score from PingOne Protect<br>*o4xxassgqz*") -- All True --> f4he7cr9jf(("EVAL<br>*f4he7cr9jf*"))
    f4he7cr9jf(("EVAL<br>*f4he7cr9jf*")) -- All True --> llvrblwi3q("Return to calling node<br>*llvrblwi3q*")
    o4xxassgqz("Risk Score from PingOne Protect<br>*o4xxassgqz*") -- All True --> tr6ask2nn2(("EVAL<br>*tr6ask2nn2*"))
    tr6ask2nn2(("EVAL<br>*tr6ask2nn2*")) -- All True --> 3b5q91z8tx("Return to calling node<br>*3b5q91z8tx*")
    o4xxassgqz("Risk Score from PingOne Protect<br>*o4xxassgqz*") -- All True --> 4tfnhsx2bw(("EVAL<br>*4tfnhsx2bw*"))
    mkork4kg94(("EVAL<br>*mkork4kg94*")) -- All True --> zmdygh0diw("Check if RiskID is empty<br>*zmdygh0diw*")
    akl8h5d22x("Get Values from PingOne Protect analysis<br>*akl8h5d22x*") -- All True --> 8fh7taswpw(("EVAL<br>*8fh7taswpw*"))
    v28wjjz61p(("EVAL<br>*v28wjjz61p*")) -- All True --> 0wx52cpso1("Go To: PingOne Protect Analysis<br>*0wx52cpso1*")
    0gubix0onw(("EVAL<br>*0gubix0onw*")) -- All True --> mxiurb5xux("Send email for threat detected<br>*mxiurb5xux*")
    ymg2y1p8tf(("EVAL<br>*ymg2y1p8tf*")) -- All True --> 8eguhqxqpn("Go To: Error<br>*8eguhqxqpn*")
    0wx52cpso1("Go To: PingOne Protect Analysis<br>*0wx52cpso1*") -- All True --> k0gh9sf1l8(("EVAL<br>*k0gh9sf1l8*"))
    4tfnhsx2bw(("EVAL<br>*4tfnhsx2bw*")) -- All True --> rsu5s043qp("Go To: Error<br>*rsu5s043qp*")
    x1gd8ktif6(("EVAL<br>*x1gd8ktif6*")) -- All False --> hhileu4ydz("Update Risk Evaluation - SUCCESS<br>*hhileu4ydz*")

    linkStyle 0 stroke:#5F84BB,stroke-width:2px;
    linkStyle 1 stroke:#5F84BB,stroke-width:2px;
    linkStyle 2 stroke:#5F84BB,stroke-width:2px;
    linkStyle 3 stroke:#5F84BB,stroke-width:2px;
    linkStyle 4 stroke:#5F84BB,stroke-width:2px;
    linkStyle 5 stroke:#5F84BB,stroke-width:2px;
    linkStyle 6 stroke:#5F84BB,stroke-width:2px;
    linkStyle 7 stroke:#5F84BB,stroke-width:2px;
    linkStyle 8 stroke:#FCBC3E,stroke-width:2px;
    linkStyle 9 stroke:#FCBC3E,stroke-width:2px;
    linkStyle 10 stroke:#FCBC3E,stroke-width:2px;
    linkStyle 11 stroke:#5F84BB,stroke-width:2px;
    linkStyle 12 stroke:#5F84BB,stroke-width:2px;
    linkStyle 13 stroke:#5F84BB,stroke-width:2px;
    linkStyle 14 stroke:#5F84BB,stroke-width:2px;
    linkStyle 15 stroke:#5F84BB,stroke-width:2px;
    linkStyle 16 stroke:#5F84BB,stroke-width:2px;
    linkStyle 17 stroke:#FCBC3E,stroke-width:2px;
    linkStyle 18 stroke:#5F84BB,stroke-width:2px;
    linkStyle 19 stroke:#5F84BB,stroke-width:2px;
    linkStyle 20 stroke:#5F84BB,stroke-width:2px;
    linkStyle 21 stroke:#5F84BB,stroke-width:2px;
    linkStyle 22 stroke:#5F84BB,stroke-width:2px;
    linkStyle 23 stroke:#5F84BB,stroke-width:2px;
    linkStyle 24 stroke:#FCBC3E,stroke-width:2px;
    linkStyle 25 stroke:#5F84BB,stroke-width:2px;
    linkStyle 26 stroke:#5F84BB,stroke-width:2px;
    linkStyle 27 stroke:#5F84BB,stroke-width:2px;
    linkStyle 28 stroke:#FCBC3E,stroke-width:2px;
    linkStyle 29 stroke:#FCBC3E,stroke-width:2px;
    linkStyle 30 stroke:#5F84BB,stroke-width:2px;
    linkStyle 31 stroke:#5F84BB,stroke-width:2px;
    linkStyle 32 stroke:#5F84BB,stroke-width:2px;
    linkStyle 33 stroke:#5F84BB,stroke-width:2px;
    linkStyle 34 stroke:#5F84BB,stroke-width:2px;
    linkStyle 35 stroke:#FCBC3E,stroke-width:2px;
    linkStyle 36 stroke:#5F84BB,stroke-width:2px;
    linkStyle 37 stroke:#5F84BB,stroke-width:2px;
    linkStyle 38 stroke:#5F84BB,stroke-width:2px;
    linkStyle 39 stroke:#FCBC3E,stroke-width:2px;
    linkStyle 40 stroke:#5F84BB,stroke-width:2px;
    linkStyle 41 stroke:#5F84BB,stroke-width:2px;
    linkStyle 42 stroke:#5F84BB,stroke-width:2px;
    linkStyle 43 stroke:#5F84BB,stroke-width:2px;
    linkStyle 44 stroke:#5F84BB,stroke-width:2px;
    linkStyle 45 stroke:#5F84BB,stroke-width:2px;
    linkStyle 46 stroke:#5F84BB,stroke-width:2px;
    linkStyle 47 stroke:#5F84BB,stroke-width:2px;
    linkStyle 48 stroke:#5F84BB,stroke-width:2px;
    linkStyle 49 stroke:#5F84BB,stroke-width:2px;
    linkStyle 50 stroke:#5F84BB,stroke-width:2px;
    linkStyle 51 stroke:#5F84BB,stroke-width:2px;
    linkStyle 52 stroke:#5F84BB,stroke-width:2px;
    linkStyle 53 stroke:#5F84BB,stroke-width:2px;
    linkStyle 54 stroke:#5F84BB,stroke-width:2px;
    linkStyle 55 stroke:#5F84BB,stroke-width:2px;
    linkStyle 56 stroke:#5F84BB,stroke-width:2px;
    linkStyle 57 stroke:#5F84BB,stroke-width:2px;
    linkStyle 58 stroke:#5F84BB,stroke-width:2px;
    linkStyle 59 stroke:#FCBC3E,stroke-width:2px;
    linkStyle 60 stroke:#5F84BB,stroke-width:2px;
    linkStyle 61 stroke:#5F84BB,stroke-width:2px;
    linkStyle 62 stroke:#5F84BB,stroke-width:2px;
    linkStyle 63 stroke:#5F84BB,stroke-width:2px;
    linkStyle 64 stroke:#5F84BB,stroke-width:2px;
    linkStyle 65 stroke:#5F84BB,stroke-width:2px;
    linkStyle 66 stroke:#5F84BB,stroke-width:2px;
    linkStyle 67 stroke:#5F84BB,stroke-width:2px;
    linkStyle 68 stroke:#5F84BB,stroke-width:2px;
    linkStyle 69 stroke:#5F84BB,stroke-width:2px;
    linkStyle 70 stroke:#5F84BB,stroke-width:2px;
    linkStyle 71 stroke:#5F84BB,stroke-width:2px;
    linkStyle 72 stroke:#5F84BB,stroke-width:2px;
    linkStyle 73 stroke:#FCBC3E,stroke-width:2px;
    linkStyle 74 stroke:#5F84BB,stroke-width:2px;
    linkStyle 75 stroke:#5F84BB,stroke-width:2px;
    linkStyle 76 stroke:#5F84BB,stroke-width:2px;
    linkStyle 77 stroke:#5F84BB,stroke-width:2px;
    linkStyle 78 stroke:#5F84BB,stroke-width:2px;
    linkStyle 79 stroke:#5F84BB,stroke-width:2px;
    linkStyle 80 stroke:#5F84BB,stroke-width:2px;
    linkStyle 81 stroke:#5F84BB,stroke-width:2px;
    linkStyle 82 stroke:#5F84BB,stroke-width:2px;
    linkStyle 83 stroke:#5F84BB,stroke-width:2px;
    linkStyle 84 stroke:#5F84BB,stroke-width:2px;
    linkStyle 85 stroke:#5F84BB,stroke-width:2px;
    linkStyle 86 stroke:#5F84BB,stroke-width:2px;
    linkStyle 87 stroke:#5F84BB,stroke-width:2px;
    linkStyle 88 stroke:#FCBC3E,stroke-width:2px;
