flowchart LR
    gjg587c8af(("EVAL<br>*gjg587c8af*")) -- Any False --> yqx4phhtcl("Go To: Error<br>*yqx4phhtcl*")
    ldx8d6ahwt(("EVAL<br>*ldx8d6ahwt*")) -- All True --> 4qv73tz0ug("Accept Agreement<br>*4qv73tz0ug*")
    6xfm9lpclg(("EVAL<br>*6xfm9lpclg*")) -- Any False --> canivkxqjq("Go To: Success<br>*canivkxqjq*")
    4h6hi1onkj(("EVAL<br>*4h6hi1onkj*")) -- All True --> 6pm1x665h0("Go To: Success<br>*6pm1x665h0*")
    h22w6agh1(("EVAL<br>*h22w6agh1*")) -- All True --> 1rvj1fvgpu("Check If Consent Status Is Accepted<br>*1rvj1fvgpu*")
    prjjhhmndv(("EVAL<br>*prjjhhmndv*")) -- All True --> 8jemlov0oc("Check User Consent Status<br>*8jemlov0oc*")
    6x74clj9zm("Check For User Consent?<br>*6x74clj9zm*") -- All True --> prjjhhmndv(("EVAL<br>*prjjhhmndv*"))
    1rvj1fvgpu("Check If Consent Status Is Accepted<br>*1rvj1fvgpu*") -- All True --> 4h6hi1onkj(("EVAL<br>*4h6hi1onkj*"))
    2vij7q7i5j(("EVAL<br>*2vij7q7i5j*")) -- All True --> v68793bc1v("Is Agreement Enabled?<br>*v68793bc1v*")
    v68793bc1v("Is Agreement Enabled?<br>*v68793bc1v*") -- All True --> 6xfm9lpclg(("EVAL<br>*6xfm9lpclg*"))
    6xfm9lpclg(("EVAL<br>*6xfm9lpclg*")) -- All True --> 6x74clj9zm("Check For User Consent?<br>*6x74clj9zm*")
    prjjhhmndv(("EVAL<br>*prjjhhmndv*")) -- Any False --> 8zvqjrwsj8("Go To: Ask for agreement<br>*8zvqjrwsj8*")
    jcpocm4del(("EVAL<br>*jcpocm4del*")) -- All True --> ph62v3m7kl("Decline Agreement<br>*ph62v3m7kl*")
    4qv73tz0ug("Accept Agreement<br>*4qv73tz0ug*") -- All True --> npztwu892l(("EVAL<br>*npztwu892l*"))
    it43isf5sm(("EVAL<br>*it43isf5sm*")) -- All True --> 8x2gjjcvxj("Check User Action<br>*8x2gjjcvxj*")
    4h6hi1onkj(("EVAL<br>*4h6hi1onkj*")) -- Any False --> 8zvqjrwsj8("Go To: Ask for agreement<br>*8zvqjrwsj8*")
    je23nstva5(("EVAL<br>*je23nstva5*")) -- All True --> 8ytvupm9en("Get Agreement<br>*8ytvupm9en*")
    8ytvupm9en("Get Agreement<br>*8ytvupm9en*") -- All True --> gjg587c8af(("EVAL<br>*gjg587c8af*"))
    npztwu892l(("EVAL<br>*npztwu892l*")) -- All True --> 3koaafiiox("Go To: Success<br>*3koaafiiox*")
    8x2gjjcvxj("Check User Action<br>*8x2gjjcvxj*") -- All True --> jcpocm4del(("EVAL<br>*jcpocm4del*"))
    qhcqow5g8y("Ask for agreement<br>*qhcqow5g8y*") -- All True --> je23nstva5(("EVAL<br>*je23nstva5*"))
    h22w6agh1(("EVAL<br>*h22w6agh1*")) -- Any False --> 8zvqjrwsj8("Go To: Ask for agreement<br>*8zvqjrwsj8*")
    8jemlov0oc("Check User Consent Status<br>*8jemlov0oc*") -- All True --> h22w6agh1(("EVAL<br>*h22w6agh1*"))
    pt563yeug9("Success<br>*pt563yeug9*") -- All True --> vomegm9y96(("EVAL<br>*vomegm9y96*"))
    vomegm9y96(("EVAL<br>*vomegm9y96*")) -- Any False --> o5cgjow8id("Return Success Response<br>*o5cgjow8id*")
    8x2gjjcvxj("Check User Action<br>*8x2gjjcvxj*") -- All True --> ldx8d6ahwt(("EVAL<br>*ldx8d6ahwt*"))
    gjg587c8af(("EVAL<br>*gjg587c8af*")) -- All True --> 0h8so1sxqq("Agreement Form<br>*0h8so1sxqq*")
    0h8so1sxqq("Agreement Form<br>*0h8so1sxqq*") -- All True --> it43isf5sm(("EVAL<br>*it43isf5sm*"))
    64hrke1krq("NOP UI Page<br>*64hrke1krq*") -- All True --> 2vij7q7i5j(("EVAL<br>*2vij7q7i5j*"))
    zv66jvh5ja("Error<br>*zv66jvh5ja*") -- All True --> 0m7rxlhf9o(("EVAL<br>*0m7rxlhf9o*"))
    0m7rxlhf9o(("EVAL<br>*0m7rxlhf9o*")) -- All True --> zgq483nez5("Return Error Response<br>*zgq483nez5*")
    npztwu892l(("EVAL<br>*npztwu892l*")) -- Any False --> hb77by4606("Go To: Error<br>*hb77by4606*")

    linkStyle 0 stroke:#FCBC3E,stroke-width:2px;
    linkStyle 1 stroke:#5F84BB,stroke-width:2px;
    linkStyle 2 stroke:#FCBC3E,stroke-width:2px;
    linkStyle 3 stroke:#5F84BB,stroke-width:2px;
    linkStyle 4 stroke:#5F84BB,stroke-width:2px;
    linkStyle 5 stroke:#5F84BB,stroke-width:2px;
    linkStyle 6 stroke:#5F84BB,stroke-width:2px;
    linkStyle 7 stroke:#5F84BB,stroke-width:2px;
    linkStyle 8 stroke:#5F84BB,stroke-width:2px;
    linkStyle 9 stroke:#5F84BB,stroke-width:2px;
    linkStyle 10 stroke:#5F84BB,stroke-width:2px;
    linkStyle 11 stroke:#FCBC3E,stroke-width:2px;
    linkStyle 12 stroke:#5F84BB,stroke-width:2px;
    linkStyle 13 stroke:#5F84BB,stroke-width:2px;
    linkStyle 14 stroke:#5F84BB,stroke-width:2px;
    linkStyle 15 stroke:#FCBC3E,stroke-width:2px;
    linkStyle 16 stroke:#5F84BB,stroke-width:2px;
    linkStyle 17 stroke:#5F84BB,stroke-width:2px;
    linkStyle 18 stroke:#5F84BB,stroke-width:2px;
    linkStyle 19 stroke:#5F84BB,stroke-width:2px;
    linkStyle 20 stroke:#5F84BB,stroke-width:2px;
    linkStyle 21 stroke:#FCBC3E,stroke-width:2px;
    linkStyle 22 stroke:#5F84BB,stroke-width:2px;
    linkStyle 23 stroke:#5F84BB,stroke-width:2px;
    linkStyle 24 stroke:#FCBC3E,stroke-width:2px;
    linkStyle 25 stroke:#5F84BB,stroke-width:2px;
    linkStyle 26 stroke:#5F84BB,stroke-width:2px;
    linkStyle 27 stroke:#5F84BB,stroke-width:2px;
    linkStyle 28 stroke:#5F84BB,stroke-width:2px;
    linkStyle 29 stroke:#5F84BB,stroke-width:2px;
    linkStyle 30 stroke:#5F84BB,stroke-width:2px;
    linkStyle 31 stroke:#FCBC3E,stroke-width:2px;
