flowchart LR
    gjg587c8af(("EVAL<br>*gjg587c8af*")) -- Any Triggers False --> yqx4phhtcl("Go To: Error<br>*yqx4phhtcl*")
    ldx8d6ahwt(("EVAL<br>*ldx8d6ahwt*")) --> 4qv73tz0ug("Accept Agreement<br>*4qv73tz0ug*")
    6xfm9lpclg(("EVAL<br>*6xfm9lpclg*")) -- Any Triggers False --> canivkxqjq("Go To: Success<br>*canivkxqjq*")
    4h6hi1onkj(("EVAL<br>*4h6hi1onkj*")) --> 6pm1x665h0("Go To: Success<br>*6pm1x665h0*")
    h22w6agh1(("EVAL<br>*h22w6agh1*")) --> 1rvj1fvgpu("Check If Consent Status Is Accepted<br>*1rvj1fvgpu*")
    prjjhhmndv(("EVAL<br>*prjjhhmndv*")) --> 8jemlov0oc("Check User Consent Status<br>*8jemlov0oc*")
    6x74clj9zm("Check For User Consent?<br>*6x74clj9zm*") --> prjjhhmndv(("EVAL<br>*prjjhhmndv*"))
    1rvj1fvgpu("Check If Consent Status Is Accepted<br>*1rvj1fvgpu*") --> 4h6hi1onkj(("EVAL<br>*4h6hi1onkj*"))
    2vij7q7i5j(("EVAL<br>*2vij7q7i5j*")) --> v68793bc1v("Is Agreement Enabled?<br>*v68793bc1v*")
    v68793bc1v("Is Agreement Enabled?<br>*v68793bc1v*") --> 6xfm9lpclg(("EVAL<br>*6xfm9lpclg*"))
    6xfm9lpclg(("EVAL<br>*6xfm9lpclg*")) --> 6x74clj9zm("Check For User Consent?<br>*6x74clj9zm*")
    prjjhhmndv(("EVAL<br>*prjjhhmndv*")) -- Any Triggers False --> 8zvqjrwsj8("Go To: Ask for agreement<br>*8zvqjrwsj8*")
    jcpocm4del(("EVAL<br>*jcpocm4del*")) --> ph62v3m7kl("Decline Agreement<br>*ph62v3m7kl*")
    4qv73tz0ug("Accept Agreement<br>*4qv73tz0ug*") --> npztwu892l(("EVAL<br>*npztwu892l*"))
    it43isf5sm(("EVAL<br>*it43isf5sm*")) --> 8x2gjjcvxj("Check User Action<br>*8x2gjjcvxj*")
    4h6hi1onkj(("EVAL<br>*4h6hi1onkj*")) -- Any Triggers False --> 8zvqjrwsj8("Go To: Ask for agreement<br>*8zvqjrwsj8*")
    je23nstva5(("EVAL<br>*je23nstva5*")) --> 8ytvupm9en("Get Agreement<br>*8ytvupm9en*")
    8ytvupm9en("Get Agreement<br>*8ytvupm9en*") --> gjg587c8af(("EVAL<br>*gjg587c8af*"))
    npztwu892l(("EVAL<br>*npztwu892l*")) --> 3koaafiiox("Go To: Success<br>*3koaafiiox*")
    8x2gjjcvxj("Check User Action<br>*8x2gjjcvxj*") --> jcpocm4del(("EVAL<br>*jcpocm4del*"))
    qhcqow5g8y("Ask for agreement<br>*qhcqow5g8y*") --> je23nstva5(("EVAL<br>*je23nstva5*"))
    h22w6agh1(("EVAL<br>*h22w6agh1*")) -- Any Triggers False --> 8zvqjrwsj8("Go To: Ask for agreement<br>*8zvqjrwsj8*")
    8jemlov0oc("Check User Consent Status<br>*8jemlov0oc*") --> h22w6agh1(("EVAL<br>*h22w6agh1*"))
    pt563yeug9("Success<br>*pt563yeug9*") --> vomegm9y96(("EVAL<br>*vomegm9y96*"))
    vomegm9y96(("EVAL<br>*vomegm9y96*")) -- Any Triggers False --> o5cgjow8id("Return Success Response<br>*o5cgjow8id*")
    8x2gjjcvxj("Check User Action<br>*8x2gjjcvxj*") --> ldx8d6ahwt(("EVAL<br>*ldx8d6ahwt*"))
    gjg587c8af(("EVAL<br>*gjg587c8af*")) --> 0h8so1sxqq("Agreement Form<br>*0h8so1sxqq*")
    0h8so1sxqq("Agreement Form<br>*0h8so1sxqq*") --> it43isf5sm(("EVAL<br>*it43isf5sm*"))
    64hrke1krq("NOP UI Page<br>*64hrke1krq*") --> 2vij7q7i5j(("EVAL<br>*2vij7q7i5j*"))
    zv66jvh5ja("Error<br>*zv66jvh5ja*") --> 0m7rxlhf9o(("EVAL<br>*0m7rxlhf9o*"))
    0m7rxlhf9o(("EVAL<br>*0m7rxlhf9o*")) --> zgq483nez5("Return Error Response<br>*zgq483nez5*")
    npztwu892l(("EVAL<br>*npztwu892l*")) -- Any Triggers False --> hb77by4606("Go To: Error<br>*hb77by4606*")

