flowchart LR
    6b03psy0ol(("EVAL<br>*6b03psy0ol*")) -- Any False --> ue7utb27ym("Error Message<br>*ue7utb27ym*")
    uizc04ybxq(("EVAL<br>*uizc04ybxq*")) -- All True --> k6hynhaety("Threat detected response.<br>*k6hynhaety*")
    uizc04ybxq(("EVAL<br>*uizc04ybxq*")) -- All False --> eagfn3lpbp("Return Success Response<br>*eagfn3lpbp*")
    y6rdbg2ky5("Create PingOne Protect Risk with user and Environment details<br>*y6rdbg2ky5*") -- All True --> vknqtnu7y2(("EVAL<br>*vknqtnu7y2*"))
    c2ulwnph9p("Detect Threat<br>*c2ulwnph9p*") -- All True --> uizc04ybxq(("EVAL<br>*uizc04ybxq*"))
    vknqtnu7y2(("EVAL<br>*vknqtnu7y2*")) -- Any False --> f994y44c9q("Error While creating a risk evaluation<br>*f994y44c9q*")
    vknqtnu7y2(("EVAL<br>*vknqtnu7y2*")) -- All True --> c2ulwnph9p("Detect Threat<br>*c2ulwnph9p*")
    6b03psy0ol(("EVAL<br>*6b03psy0ol*")) -- All True --> y6rdbg2ky5("Create PingOne Protect Risk with user and Environment details<br>*y6rdbg2ky5*")
    qbf0qv8qi0("Flow Configuration Check<br>*qbf0qv8qi0*") -- All True --> 6b03psy0ol(("EVAL<br>*6b03psy0ol*"))

    linkStyle 0 stroke:#FCBC3E,stroke-width:2px;
    linkStyle 1 stroke:#5F84BB,stroke-width:2px;
    linkStyle 2 stroke:#FCBC3E,stroke-width:2px;
    linkStyle 3 stroke:#5F84BB,stroke-width:2px;
    linkStyle 4 stroke:#5F84BB,stroke-width:2px;
    linkStyle 5 stroke:#FCBC3E,stroke-width:2px;
    linkStyle 6 stroke:#5F84BB,stroke-width:2px;
    linkStyle 7 stroke:#5F84BB,stroke-width:2px;
    linkStyle 8 stroke:#5F84BB,stroke-width:2px;
