flowchart LR
    6b03psy0ol(("EVAL<br>*6b03psy0ol*")) -- Any Triggers False --> ue7utb27ym("Error Message<br>*ue7utb27ym*")
    uizc04ybxq(("EVAL<br>*uizc04ybxq*")) --> k6hynhaety("Threat detected response.<br>*k6hynhaety*")
    uizc04ybxq(("EVAL<br>*uizc04ybxq*")) -- All Triggers False --> eagfn3lpbp("Return Success Response<br>*eagfn3lpbp*")
    y6rdbg2ky5("Create PingOne Protect Risk with user and Environment details<br>*y6rdbg2ky5*") --> vknqtnu7y2(("EVAL<br>*vknqtnu7y2*"))
    c2ulwnph9p("Detect Threat<br>*c2ulwnph9p*") --> uizc04ybxq(("EVAL<br>*uizc04ybxq*"))
    vknqtnu7y2(("EVAL<br>*vknqtnu7y2*")) -- Any Triggers False --> f994y44c9q("Error While creating a risk evaluation<br>*f994y44c9q*")
    vknqtnu7y2(("EVAL<br>*vknqtnu7y2*")) --> c2ulwnph9p("Detect Threat<br>*c2ulwnph9p*")
    6b03psy0ol(("EVAL<br>*6b03psy0ol*")) -- All Triggers False --> y6rdbg2ky5("Create PingOne Protect Risk with user and Environment details<br>*y6rdbg2ky5*")
    qbf0qv8qi0("Flow Configuration Check<br>*qbf0qv8qi0*") --> 6b03psy0ol(("EVAL<br>*6b03psy0ol*"))

